#ifndef TG_HOST_TESTS_MEMBERS_STATUS_TEXT_TESTS_H
#define TG_HOST_TESTS_MEMBERS_STATUS_TEXT_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGMembersStatusTextTestBannedWithCustomTitlePrefersBanOverTitle(void);
TGTestOutcome TGMembersStatusTextTestBannedWithDurationAndCustomTitleShowsDurationNotTitle(void);
TGTestOutcome TGMembersStatusTextTestRestrictedWithCustomTitlePrefersRestrictionOverTitle(void);
TGTestOutcome TGMembersStatusTextTestRestrictedWithDurationAndCustomTitleShowsDurationNotTitle(void);
TGTestOutcome TGMembersStatusTextTestAdministratorWithCustomTitleStillShowsTitle(void);
TGTestOutcome TGMembersStatusTextTestPlainMemberWithCustomTitleStillShowsTitle(void);
TGTestOutcome TGMembersStatusTextTestCreatorWithoutCustomTitleShowsOwner(void);
TGTestOutcome TGMembersStatusTextTestPlainMemberWithoutCustomTitleShowsMemberFallback(void);
TGTestOutcome TGMembersStatusTextTestMemberWithKnownPresencePrefersPresenceOverRoleWord(void);
TGTestOutcome TGMembersStatusTextTestAdministratorWithKnownPresenceShowsPresenceNotRoleWord(void);
TGTestOutcome TGMembersStatusTextTestBannedMemberShowsNoRoleLabel(void);

#endif
