#ifndef TG_HOST_TESTS_RECOVERY_EMAIL_CODE_CONFIRMATION_TESTS_H
#define TG_HOST_TESTS_RECOVERY_EMAIL_CODE_CONFIRMATION_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGRecoveryEmailCodeConfirmationTestNonDictionaryStateIsNotConfirmed(void);
TGTestOutcome TGRecoveryEmailCodeConfirmationTestMissingPatternIsConfirmed(void);
TGTestOutcome TGRecoveryEmailCodeConfirmationTestEmptyPatternIsConfirmed(void);
TGTestOutcome TGRecoveryEmailCodeConfirmationTestNonStringPatternIsConfirmed(void);
TGTestOutcome TGRecoveryEmailCodeConfirmationTestNonEmptyPatternIsNotConfirmed(void);

#endif
