#ifndef TG_HOST_TESTS_FLATTEN_NOTIFICATIONS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_NOTIFICATIONS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenNotificationsTestScopeTypeMapsGroupsChannelsAndDefault(void);
TGTestOutcome TGFlattenNotificationsTestReactionSourceMapsAllContactsAndDefault(void);
TGTestOutcome TGFlattenNotificationsTestScopeSettingsFromComposesFullInput(void);
TGTestOutcome TGFlattenNotificationsTestScopeSettingsFromFillsDefaultsForEmptyInput(void);
TGTestOutcome TGFlattenNotificationsTestChatSettingsFromComposesFullInput(void);
TGTestOutcome TGFlattenNotificationsTestChatSettingsFromFillsDefaultsForEmptyInput(void);
TGTestOutcome TGFlattenNotificationsTestPickPrefersChangesOverCurrentAndFallsBackToZero(void);
TGTestOutcome TGFlattenNotificationsTestScopeMutedOverridesSetsMuteForWhenMutedTrueWithoutMuteFor(void);
TGTestOutcome TGFlattenNotificationsTestScopeMutedOverridesSetsZeroMuteForWhenMutedFalseWithoutMuteFor(void);
TGTestOutcome TGFlattenNotificationsTestScopeMutedOverridesDefersToExplicitMuteFor(void);
TGTestOutcome TGFlattenNotificationsTestScopeMutedOverridesIsEmptyForNonDictionaryChanges(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesSetsMuteForAndClearsUseDefaultWhenMutedTrue(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesSetsZeroMuteForWhenMutedFalse(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesDefersToExplicitMuteFor(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesClearsUseDefaultFlagsWhenTheirValuesChange(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesDoesNotOverrideWhenUseDefaultFlagsAreExplicit(void);
TGTestOutcome TGFlattenNotificationsTestChatMutedOverridesIsEmptyForNonDictionaryChanges(void);
TGTestOutcome TGFlattenNotificationsTestSoundIdsSurviveArrivingAsStrings(void);

TGTestOutcome TGFlattenNotificationsTestReactionSettingsReadBackFromTheWire(void);
TGTestOutcome TGFlattenNotificationsTestReactionSettingsMergeKeepsUntouchedFields(void);
TGTestOutcome TGFlattenNotificationsTestReactionSettingsPayloadRoundTrips(void);

#endif
