#ifndef TG_HOST_TESTS_STRING_TRUNCATION_TESTS_H
#define TG_HOST_TESTS_STRING_TRUNCATION_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGStringTruncationTestToIndexBelowLengthIsUnchanged(void);
TGTestOutcome TGStringTruncationTestToIndexAtExactSequenceBoundaryIsUnchanged(void);
TGTestOutcome TGStringTruncationTestToIndexInsideSurrogatePairDropsWholeCharacter(void);
TGTestOutcome TGStringTruncationTestToIndexAtOrAboveLengthReturnsWholeString(void);
TGTestOutcome TGStringTruncationTestToIndexInsideZWJSequenceDropsWholeCluster(void);
TGTestOutcome TGStringTruncationTestFromIndexZeroReturnsWholeString(void);
TGTestOutcome TGStringTruncationTestFromIndexAtExactSequenceBoundaryIsUnchanged(void);
TGTestOutcome TGStringTruncationTestFromIndexInsideSurrogatePairSkipsWholeCharacter(void);
TGTestOutcome TGStringTruncationTestFromIndexAtOrAboveLengthReturnsEmptyString(void);
TGTestOutcome TGStringTruncationTestFirstCharacterKeepsWholeGlyphs(void);
TGTestOutcome TGStringTruncationTestFirstCharacterCaseChangeKeepsTheRest(void);

#endif
