#ifndef TG_HOST_TESTS_FLATTEN_CHAT_MANAGEMENT_TESTS_H
#define TG_HOST_TESTS_FLATTEN_CHAT_MANAGEMENT_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenChatManagementTestStatusNameMapsCreatorAndAdministrator(void);
TGTestOutcome TGFlattenChatManagementTestStatusNameFallsBackToMemberForOtherKnownStatuses(void);
TGTestOutcome TGFlattenChatManagementTestStatusNameFallsBackToMemberForUnknownType(void);
TGTestOutcome TGFlattenChatManagementTestFlatRightsOwnerGrantsAllRightsExceptAnonymousWhichReadsRawDict(void);
TGTestOutcome TGFlattenChatManagementTestFlatRightsAdministratorReflectsPartialRightsDict(void);
TGTestOutcome TGFlattenChatManagementTestFlatRightsPlainMemberIsAllFalse(void);
TGTestOutcome TGFlattenChatManagementTestFlatRightsMissingRightsDictDoesNotCrash(void);
TGTestOutcome TGFlattenChatManagementTestFlatRightsCustomTitleHandling(void);

TGTestOutcome TGFlattenChatManagementTestFlatComposerPermissionsAdminOrOwnerGrantsEverythingAndClearsSlowMode(void);
TGTestOutcome TGFlattenChatManagementTestFlatComposerPermissionsPlainMemberReadsEachKeyFromTheRawDict(void);
TGTestOutcome TGFlattenChatManagementTestFlatComposerPermissionsMissingOrNilMemberPermissionsIsAllFalse(void);
TGTestOutcome TGFlattenChatManagementTestFlatComposerPermissionsSlowModeSecondsRemainingIsRoundedUpAndClamped(void);

#endif
