#ifndef TG_HOST_TESTS_FLATTEN_GIFS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_GIFS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenGifsTestWebmFormatSuppressesThumbId(void);
TGTestOutcome TGFlattenGifsTestTgsFormatSuppressesThumbId(void);
TGTestOutcome TGFlattenGifsTestMpeg4FormatKeepsThumbIdAndReportsVideo(void);
TGTestOutcome TGFlattenGifsTestMissingThumbnailYieldsEmptyThumbFields(void);

#endif
