#ifndef TG_HOST_TESTS_FLATTEN_BUSINESS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_BUSINESS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenBusinessTestOpeningHoursClampsMinuteZero(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursClampsDayBoundary(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursHandlesMinuteWrappingIntoNextDay(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursOvernightIntervalRoundTripsWithoutTruncation(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursOvernightWrapsFromSundayToMonday(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursReturnsNilForNilInput(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursDefaultsUnlistedDaysClosed(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursAccumulatesSplitIntervalsInsteadOfOverwriting(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursDetectsOvernightCollisionAsComplex(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursSingleCarryoverIsNotFlaggedComplex(void);
TGTestOutcome TGFlattenBusinessTestOpeningHoursSimpleWeeklyScheduleIsNotComplex(void);
TGTestOutcome TGFlattenBusinessTestAwayScheduleAlways(void);
TGTestOutcome TGFlattenBusinessTestAwayScheduleOutsideOfOpeningHours(void);
TGTestOutcome TGFlattenBusinessTestAwayScheduleCustomDates(void);
TGTestOutcome TGFlattenBusinessTestAwayReturnsNilForNilInput(void);
TGTestOutcome TGFlattenBusinessTestRightsRoundTripsFullSet(void);
TGTestOutcome TGFlattenBusinessTestRightsRoundTripsPartialSet(void);
TGTestOutcome TGFlattenBusinessTestRecipientsRoundTripsBothDirections(void);
TGTestOutcome TGFlattenBusinessTestRecipientsPreservesExcludeSelectedTrueOnRoundTrip(void);
TGTestOutcome TGFlattenBusinessTestFlattenLinkComposesRealisticPayload(void);
TGTestOutcome TGFlattenBusinessTestFlattenLinkReturnsNilForMalformedInput(void);
TGTestOutcome TGFlattenBusinessTestFlattenLinkPreservesTextEntities(void);

#endif
