#ifndef TG_HOST_TESTS_CONTACT_NAME_TESTS_H
#define TG_HOST_TESTS_CONTACT_NAME_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGContactNameTestFullFirstAndLastName(void);
TGTestOutcome TGContactNameTestFirstNameOnly(void);
TGTestOutcome TGContactNameTestLastNameOnly(void);
TGTestOutcome TGContactNameTestBlankNameFallsThroughToUsername(void);
TGTestOutcome TGContactNameTestBlankNameAndUsernameFallsThroughToPhone(void);
TGTestOutcome TGContactNameTestEverythingMissingReturnsEmptyString(void);
TGTestOutcome TGContactNameTestWrongTypeValueDoesNotCrash(void);
TGTestOutcome TGContactStringTestReturnsEmptyForMissingOrWrongTypeKey(void);

#endif
