#ifndef TG_HOST_TESTS_FLATTEN_CONTACTS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_CONTACTS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenContactsTestBirthdateWithDayMonthAndYear(void);
TGTestOutcome TGFlattenContactsTestBirthdateWithDayAndMonthOnly(void);
TGTestOutcome TGFlattenContactsTestBirthdateRejectsInvalidDay(void);
TGTestOutcome TGFlattenContactsTestBirthdateRejectsInvalidMonth(void);
TGTestOutcome TGFlattenContactsTestBirthdateRejectsNonDictionaryInput(void);
TGTestOutcome TGFlattenContactsTestFlatUserComposesRealisticPayload(void);
TGTestOutcome TGFlattenContactsTestFlatUserRejectsWrongType(void);
TGTestOutcome TGFlattenContactsTestFirstUsernamePrefersActiveUsername(void);
TGTestOutcome TGFlattenContactsTestFirstUsernameFallsBackToEditableUsername(void);
TGTestOutcome TGFlattenContactsTestFirstUsernameEmptyWhenNoUsernames(void);
TGTestOutcome TGFlattenContactsTestProfileTabNameMapsEachKnownTab(void);
TGTestOutcome TGFlattenContactsTestProfileTabNameRejectsUnrelatedType(void);
TGTestOutcome TGFlattenContactsTestBirthdateIsTodayMatchesTodaysDayAndMonth(void);
TGTestOutcome TGFlattenContactsTestBirthdateIsTodayRejectsADifferentMonth(void);
TGTestOutcome TGFlattenContactsTestBirthdateIsTodayRejectsInvalidDayOrMonth(void);
TGTestOutcome TGFlattenContactsTestBirthdateIsTodayRejectsNonDictionaryInput(void);

#endif
