#ifndef TG_HOST_TESTS_FLATTEN_CHAT_STATE_TESTS_H
#define TG_HOST_TESTS_FLATTEN_CHAT_STATE_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenChatStateTestScopeTypeMapsGroupsChannelsAndDefault(void);
TGTestOutcome TGFlattenChatStateTestScopeNameMapsGroupsChannelsAndDefault(void);
TGTestOutcome TGFlattenChatStateTestScopeForChatFlagsMapsChannelGroupAndPrivate(void);
TGTestOutcome TGFlattenChatStateTestEffectiveChatMutedUsesScopeDefaultWhenUseDefaultIsTrue(void);
TGTestOutcome TGFlattenChatStateTestEffectiveChatMutedUsesChatOwnMuteForWhenUseDefaultIsFalse(void);
TGTestOutcome TGFlattenChatStateTestFileObjectStateFlattensFullFileDict(void);
TGTestOutcome TGFlattenChatStateTestFileObjectStateFallsBackToExpectedSizeWhenSizeIsZero(void);
TGTestOutcome TGFlattenChatStateTestFileObjectStateFillsDefaultsForMissingLocalAndFields(void);
TGTestOutcome TGFlattenChatStateTestFileObjectStateReturnsNilForNonDictionaryInput(void);

#endif
