#ifndef TG_HOST_TESTS_FLATTEN_REACTIONS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_REACTIONS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenReactionsTestUnavailabilityForAnonymousAdministrator(void);
TGTestOutcome TGFlattenReactionsTestUnavailabilityForGuest(void);
TGTestOutcome TGFlattenReactionsTestUnavailabilityForRestricted(void);
TGTestOutcome TGFlattenReactionsTestUnavailabilityFallsBackForUnknownReason(void);
TGTestOutcome TGFlattenReactionsTestUnavailabilityFallsBackForNilOrNonDictionaryReason(void);

TGTestOutcome TGFlattenReactionsTestChipSignatureComposesMultipleChips(void);
TGTestOutcome TGFlattenReactionsTestChipSignatureTreatsMissingEmojiAsEmptyString(void);
TGTestOutcome TGFlattenReactionsTestChipSignatureSkipsNonDictionaryEntries(void);
TGTestOutcome TGFlattenReactionsTestChipSignatureReturnsEmptyForNilOrNonArrayOrEmptyInput(void);

TGTestOutcome TGFlattenReactionsTestSenderIdForUser(void);
TGTestOutcome TGFlattenReactionsTestSenderIdForChat(void);
TGTestOutcome TGFlattenReactionsTestSenderIdReturnsZeroForNilOrNonDictionaryOrEmptySender(void);

TGTestOutcome TGFlattenReactionsTestUserQuotaIsOneForNonPremium(void);
TGTestOutcome TGFlattenReactionsTestUserQuotaIsThreeForPremium(void);
TGTestOutcome TGFlattenReactionsTestHasRoomForMoreDeniesNonPremiumUserAtQuota(void);
TGTestOutcome TGFlattenReactionsTestHasRoomForMoreAllowsPremiumUserBelowQuotaWithChatRoom(void);
TGTestOutcome TGFlattenReactionsTestHasRoomForMoreDeniesWhenChatWideCapIsReachedEvenUnderUserQuota(void);
TGTestOutcome TGFlattenReactionsTestHasRoomForMoreTreatsNonPositiveChatMaxAsOne(void);

TGTestOutcome TGFlattenReactionsTestTypeExistsOnMessageFindsMatchingEmoji(void);
TGTestOutcome TGFlattenReactionsTestTypeExistsOnMessageReturnsNoWhenAbsent(void);
TGTestOutcome TGFlattenReactionsTestTypeExistsOnMessageReturnsNoForNilOrEmptyInputs(void);

TGTestOutcome TGFlattenReactionsTestChatIsSavedMessagesTrueWhenChatIdMatches(void);
TGTestOutcome TGFlattenReactionsTestChatIsSavedMessagesFalseWhenChatIdDiffers(void);
TGTestOutcome TGFlattenReactionsTestChatIsSavedMessagesFalseWhenEitherIdIsZero(void);

TGTestOutcome TGFlattenReactionsTestSavedMessagesTagLookupKeyPrefersEmoji(void);
TGTestOutcome TGFlattenReactionsTestSavedMessagesTagLookupKeyBuildsCustomKeyWhenNoEmoji(void);
TGTestOutcome TGFlattenReactionsTestSavedMessagesTagLookupKeyReturnsNilWhenNeitherIsSet(void);

#endif
