#ifndef TG_HOST_TESTS_ACCOUNT_MANAGER_TESTS_H
#define TG_HOST_TESTS_ACCOUNT_MANAGER_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGAccountManagerTestFreshManagerHasNoAccountsAndSlotZeroIsFree(void);
TGTestOutcome TGAccountManagerTestFirstFreeSlotSkipsOccupiedSlots(void);
TGTestOutcome TGAccountManagerTestCanAddAccountFalseWhenAllSlotsOccupied(void);
TGTestOutcome TGAccountManagerTestAccountsReturnsDefensiveCopies(void);
TGTestOutcome TGAccountManagerTestAccountForSlotReturnsNilForUnknownSlot(void);
TGTestOutcome TGAccountManagerTestCurrentAccountReflectsCurrentSlot(void);
TGTestOutcome TGAccountManagerTestNoteUnreadCountUpdatesExistingRecord(void);
TGTestOutcome TGAccountManagerTestNoteUnreadCountNoOpWhenNoRecordForCurrentSlot(void);
TGTestOutcome TGAccountManagerTestRememberCurrentAccountNoOpWhenClientHasNoMe(void);
TGTestOutcome TGAccountManagerTestRememberCurrentAccountCreatesRecordFromClientMe(void);
TGTestOutcome TGAccountManagerTestRememberCurrentAccountSumsUnreadExcludingMutedChats(void);
TGTestOutcome TGAccountManagerTestRememberCurrentAccountClearsAddingAccountWhenNotSwitching(void);
TGTestOutcome TGAccountManagerTestRememberCurrentAccountKeepsAddingAccountWhileSwitching(void);
TGTestOutcome TGAccountManagerTestSwitchToSlotUpdatesCurrentSlotAndDrivesClientLifecycle(void);
TGTestOutcome TGAccountManagerTestSwitchToSlotNoOpForInvalidSlot(void);
TGTestOutcome TGAccountManagerTestSwitchToSlotNoOpWhenAlreadyOnSlotAndNotAddingAccount(void);
TGTestOutcome TGAccountManagerTestSwitchToSlotIsNoOpWhileAlreadySwitching(void);
TGTestOutcome TGAccountManagerTestSwitchToSlotTriggersLogOutWhenAwaitingSignOutMatchesTarget(void);
TGTestOutcome TGAccountManagerTestBeginAddingAccountSwitchesToFirstFreeSlotAndKeepsAddingFlag(void);
TGTestOutcome TGAccountManagerTestBeginAddingAccountNoOpWhenNoFreeSlot(void);
TGTestOutcome TGAccountManagerTestCancelAddingAccountReturnsToPreviousSlotWhenPossible(void);
TGTestOutcome TGAccountManagerTestCancelAddingAccountNoOpWhenNotAddingAccount(void);
TGTestOutcome TGAccountManagerTestCancelAddingAccountDoesNotSwitchWhenNoValidPreviousSlot(void);
TGTestOutcome TGAccountManagerTestSignOutOfSlotNoOpForCurrentSlot(void);
TGTestOutcome TGAccountManagerTestSignOutOfSlotSwitchesToTargetAndLogsOut(void);
TGTestOutcome TGAccountManagerTestHandleLogOutFallsBackToPreferredSlotWhenValid(void);
TGTestOutcome TGAccountManagerTestHandleLogOutForgetsRecordAndReturnsNoWhenNoOtherAccountsExist(void);
TGTestOutcome TGAccountManagerTestScopeForSlotIsNilForNonPositiveSlot(void);

#endif
