#ifndef TG_HOST_TESTS_FLATTEN_FORUMS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_FORUMS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenForumsTestMessagePreviewForPhoto(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForVideo(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForVideoNote(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForVoiceNote(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForAudio(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForDocument(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForSticker(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForAnimation(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForLocation(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForContact(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForPoll(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForTopicCreated(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForTopicEditedRenamed(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForTopicEditedIconOnly(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewForTopicEditedWithNoDetail(void);
TGTestOutcome TGFlattenForumsTestMessagePreviewFallsBackForUnknownKind(void);
TGTestOutcome TGFlattenForumsTestFlattenTopicComposesFullPayload(void);
TGTestOutcome TGFlattenForumsTestFlattenTopicDefaultsForMinimalPayload(void);
TGTestOutcome TGFlattenForumsTestTopicIdForNotificationExtractsForumTopicId(void);
TGTestOutcome TGFlattenForumsTestTopicIdForNotificationIsZeroForNonForumTopic(void);
TGTestOutcome TGFlattenForumsTestTopicIdForNotificationIsZeroForNonMessageNotification(void);
TGTestOutcome TGFlattenForumsTestTopicRowsNameEveryKind(void);

#endif
