#ifndef TG_HOST_TESTS_FLATTEN_USER_STATUS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_USER_STATUS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenUserStatusTestEmojiIconCarriesScalarFields(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconNilGiftTitleFallsBackToEmptyString(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconNilStickerOmitsFileIds(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconFileIdsPassThroughWhenNumeric(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconIgnoresNonNumericFileIds(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconTgsFormatIsAnimatedAndTgs(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconWebmFormatIsNeitherAnimatedNorTgs(void);
TGTestOutcome TGFlattenUserStatusTestEmojiIconStaticFormatIsNeitherAnimatedNorTgs(void);
TGTestOutcome TGFlattenUserStatusTestLastSeenNonPositiveIsLongTimeAgo(void);
TGTestOutcome TGFlattenUserStatusTestLastSeenNowContainsTodayLabelAndTime(void);
TGTestOutcome TGFlattenUserStatusTestLastSeenYesterdayContainsYesterdayLabel(void);
TGTestOutcome TGFlattenUserStatusTestLastSeenWithinWeekUsesWeekdayName(void);
TGTestOutcome TGFlattenUserStatusTestLastSeenOlderThanWeekUsesDateFormat(void);
TGTestOutcome TGFlattenUserStatusTestMergeOrdersThemedBeforeRecentBeforeDefault(void);
TGTestOutcome TGFlattenUserStatusTestMergeDedupesAcrossTiers(void);
TGTestOutcome TGFlattenUserStatusTestMergeDropsZeroIds(void);
TGTestOutcome TGFlattenUserStatusTestMergeCapsAtLimit(void);
TGTestOutcome TGFlattenUserStatusTestMergeTreatsNilArraysAsEmpty(void);
TGTestOutcome TGFlattenUserStatusTestStatusInfoForEmptyTypeHasNoFabricatedText(void);
TGTestOutcome TGFlattenUserStatusTestStatusInfoForUnknownTypeHasNoFabricatedText(void);
TGTestOutcome TGFlattenUserStatusTestStatusInfoForOnlineIsUnaffected(void);
TGTestOutcome TGFlattenUserStatusTestStatusInfoForOfflineCarriesWasOnline(void);
TGTestOutcome TGFlattenUserStatusTestStatusInfoForRecentlyCarriesHiddenFlag(void);

#endif
