#ifndef TG_HOST_TESTS_ITEM_BUILDERS_TESTS_H
#define TG_HOST_TESTS_ITEM_BUILDERS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGItemBuildersTestStorageDownloadsNamesAFileFromTheBestSourceItHas(void);
TGTestOutcome TGItemBuildersTestStorageDownloadsDetailReadsProgressCompletionAndPause(void);
TGTestOutcome TGItemBuildersTestStorageDownloadsFixedRowsCarryTheirOwnKind(void);
TGTestOutcome TGItemBuildersTestStarsListChoosesSubtitleOverValue(void);
TGTestOutcome TGItemBuildersTestStarsListRefusesABadgeRowAndReadsTheFlags(void);
TGTestOutcome TGItemBuildersTestStarsListStatusRowTextFollowsTheState(void);
TGTestOutcome TGItemBuildersTestConnectedWebsitesTitleFallsBackToDomainThenWebsite(void);
TGTestOutcome TGItemBuildersTestConnectedWebsitesDetailJoinsOnlyThePartsThatApply(void);
TGTestOutcome TGItemBuildersTestHiddenStoriesNamesADeletedAccount(void);
TGTestOutcome TGItemBuildersTestPrivacyContactPickerComposesAName(void);
TGTestOutcome TGItemBuildersTestPrivacyContactPickerMarksOnlyTheChosenIds(void);
TGTestOutcome TGItemBuildersTestNewGroupMembersMarksOnlyTheSelectedIds(void);
TGTestOutcome TGItemBuildersTestUsernameRowsPrefixTheHandle(void);
TGTestOutcome TGItemBuildersTestOwnedSetsCountsStickersAndPicksACover(void);
TGTestOutcome TGItemBuildersTestStoryViewersJoinsTheReactionEmoji(void);
TGTestOutcome TGItemBuildersTestCallsGroupReadsCountKindAndDirection(void);
TGTestOutcome TGItemBuildersTestGroupMemberFallsBackToUnknownName(void);
TGTestOutcome TGItemBuildersTestEveryBuilderNamesItsCellAndKind(void);

TGTestOutcome TGItemBuildersTestProfileDetailMarksWhatARowCanDo(void);
TGTestOutcome TGItemBuildersTestProfileDetailSongCarriesItsPlaybackGlyph(void);

TGTestOutcome TGItemBuildersTestSearchResultSplitsAContactName(void);
TGTestOutcome TGItemBuildersTestSearchResultMessageAndHashtagRows(void);

#endif
