#ifndef TG_LAYOUT_BUILDER_TESTS_H
#define TG_LAYOUT_BUILDER_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGLayoutBuilderTestPhotoStampSitsBesideTheBubble(void);
TGTestOutcome TGLayoutBuilderTestPhotoBubbleHugsThePicture(void);
TGTestOutcome TGLayoutBuilderTestForwardedPhotoFitsItsForwardLine(void);
TGTestOutcome TGLayoutBuilderTestCaptionWrapsAtThePictureWidth(void);
TGTestOutcome TGLayoutBuilderTestAlbumCaptionWrapsAtTheMosaicWidth(void);
TGTestOutcome TGLayoutBuilderTestWideAlbumLeavesRoomForItsStamp(void);
TGTestOutcome TGLayoutBuilderTestEveryKindLeavesItsStampRoomWhenIndented(void);
TGTestOutcome TGLayoutBuilderTestAnAvatarNeverPushesABubbleOffTheTable(void);
TGTestOutcome TGLayoutBuilderTestBubbleWithoutArtworkKeepsItsTailAndCorners(void);
TGTestOutcome TGLayoutBuilderTestChannelPostShowsCommentsRow(void);
TGTestOutcome TGLayoutBuilderTestOrdinaryMessageHasNoCommentsRow(void);
TGTestOutcome TGLayoutBuilderTestItemBuilderCarriesDestructFields(void);
TGTestOutcome TGLayoutBuilderTestAlbumChannelPostShowsCommentsRow(void);
TGTestOutcome TGLayoutBuilderTestZeroCommentThreadShowsLeaveACommentRow(void);
TGTestOutcome TGLayoutBuilderTestPollRetractRowRespectsAllowsRevoting(void);
TGTestOutcome TGLayoutBuilderTestStickerSitsOnTheWallpaperWithNoBubbleChrome(void);
TGTestOutcome TGLayoutBuilderTestForwardedWallpaperContentReservesAHeader(void);
TGTestOutcome TGLayoutBuilderTestQuotedWallpaperContentSitsBelowTheQuote(void);
TGTestOutcome TGLayoutBuilderTestEveryBuilderKeepsThePlateBesideTheBubble(void);
TGTestOutcome TGLayoutBuilderTestServiceLineHasNoStampAndARoundedPlate(void);
TGTestOutcome TGLayoutBuilderTestVideoNoteWithoutASizeIsStillARoundNote(void);

#endif
