#ifndef TG_HOST_TESTS_DATE_UTILS_TESTS_H
#define TG_HOST_TESTS_DATE_UTILS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGDateUtilsTestShortTimeIsDeterministicForSameInput(void);
TGTestOutcome TGDateUtilsTestShortTimeReflectsMinuteChange(void);
TGTestOutcome TGDateUtilsTestDialogTimeReflectsMonthAndDay(void);
TGTestOutcome TGDateUtilsTestDayOfMonthMatchesCalendarDayAndOutParam(void);
TGTestOutcome TGDateUtilsTestDayOfWeekMatchesWeekdayName(void);
TGTestOutcome TGDateUtilsTestMessageListDateSameDayMatchesShortTime(void);
TGTestOutcome TGDateUtilsTestMessageListDateWeekBoundaryBehavior(void);
TGTestOutcome TGDateUtilsTestLastSeenTodayContainsTodayLabel(void);
TGTestOutcome TGDateUtilsTestLastSeenYesterdayContainsYesterdayLabel(void);
TGTestOutcome TGDateUtilsTestLastSeenOlderThanYesterdayOmitsRelativeLabels(void);
TGTestOutcome TGDateUtilsTestLastSeenShortMatchesLastSeen(void);
TGTestOutcome TGDateUtilsTestRelativeLastSeenJustNowForRecentTimestamp(void);
TGTestOutcome TGDateUtilsTestRelativeLastSeenMinuteSingularPluralBoundary(void);
TGTestOutcome TGDateUtilsTestRelativeLastSeenHourBoundaryAtSixtyMinutes(void);
TGTestOutcome TGDateUtilsTestUntilTodayAndTomorrowLabels(void);
TGTestOutcome TGDateUtilsTestUntilTwoDaysAheadOmitsTodayAndTomorrowLabels(void);
TGTestOutcome TGDateUtilsTestDefensiveInputsDoNotCrashAcrossFunctions(void);
TGTestOutcome TGDateUtilsTestDayDividerReadsAsADate(void);
TGTestOutcome TGDateUtilsTestWeekdayAndShortDateAreTheAppsOwnWords(void);
TGTestOutcome TGDateUtilsTestMonthAndFullDateAreTheAppsOwnWords(void);
TGTestOutcome TGDateUtilsTestFullDateAndTimeCarriesBothHalves(void);
TGTestOutcome TGDateUtilsTestClockSplitsIntoNumberAndMarker(void);

#endif
