#ifndef TG_HOST_TESTS_CALL_STUN_TESTS_H
#define TG_HOST_TESTS_CALL_STUN_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGCallStunTestMessageTypeOfValidBindingRequest(void);
TGTestOutcome TGCallStunTestMessageTypeOfValidBindingResponse(void);
TGTestOutcome TGCallStunTestMessageTypeOfRejectsBadMagicCookie(void);
TGTestOutcome TGCallStunTestMessageTypeOfRejectsTooShortPacket(void);
TGTestOutcome TGCallStunTestMessageTypeOfRejectsReservedClassBits(void);
TGTestOutcome TGCallStunTestBindingRequestHeaderAndCookie(void);
TGTestOutcome TGCallStunTestBindingRequestPriorityAttributeIsFixedValue(void);
TGTestOutcome TGCallStunTestBindingRequestIceControllingEncodesTieBreaker(void);
TGTestOutcome TGCallStunTestBindingRequestUseCandidateAttributePresentWhenRequested(void);
TGTestOutcome TGCallStunTestBindingRequestUseCandidateAttributeAbsentWhenNotRequested(void);
TGTestOutcome TGCallStunTestBindingRequestUsernameAttributeMatchesInput(void);
TGTestOutcome TGCallStunTestBindingRequestMessageIntegrityMatchesIndependentHmac(void);
TGTestOutcome TGCallStunTestBindingRequestFingerprintMatchesIndependentCrc32(void);
TGTestOutcome TGCallStunTestBindingRequestHeaderLengthMatchesAttributeBytes(void);
TGTestOutcome TGCallStunTestBindingResponseCopiesTransactionIdFromRequest(void);
TGTestOutcome TGCallStunTestBindingResponseTooShortRequestReturnsNil(void);
TGTestOutcome TGCallStunTestBindingResponseXorMappedAddressRoundTrips(void);
TGTestOutcome TGCallStunTestBindingResponseEmptyAddressYieldsZeroAddress(void);
TGTestOutcome TGCallStunTestBindingResponseMessageIntegrityMatchesIndependentHmac(void);

#endif
