#ifndef TG_HOST_TESTS_FLATTEN_CHAT_LIST_TESTS_H
#define TG_HOST_TESTS_FLATTEN_CHAT_LIST_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenChatListTestPlainTextReturnsFlatStringUnchanged(void);
TGTestOutcome TGFlattenChatListTestPlainTextUnwrapsOneLevelOfNesting(void);
TGTestOutcome TGFlattenChatListTestPlainTextUnwrapsMultipleLevelsOfNesting(void);
TGTestOutcome TGFlattenChatListTestPlainTextReturnsEmptyForNilAndEmptyInput(void);
TGTestOutcome TGFlattenChatListTestPlainTextSurvivesDeepRecursion(void);
TGTestOutcome TGFlattenChatListTestChatListObjectRoundTripsMain(void);
TGTestOutcome TGFlattenChatListTestChatListObjectRoundTripsArchive(void);
TGTestOutcome TGFlattenChatListTestChatListObjectRoundTripsFolder(void);
TGTestOutcome TGFlattenChatListTestUnreadContributionReturnsRawCountWhenPositive(void);
TGTestOutcome TGFlattenChatListTestUnreadContributionReturnsOneForMarkedUnreadZeroCount(void);
TGTestOutcome TGFlattenChatListTestUnreadContributionReturnsZeroWhenNeitherUnreadNorMarked(void);
TGTestOutcome TGFlattenChatListTestUnreadContributionHandlesNonDictionaryInput(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionExcludesMutedChatWithNoUnreadMention(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionKeepsMutedChatWithUnreadMention(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionExcludesReadChatWithNoUnreadMention(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionKeepsReadChatWithUnreadMention(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionArchivedIsNeverOverriddenByUnreadMention(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionAllowsNonExcludedChat(void);
TGTestOutcome TGFlattenChatListTestFolderExclusionHandlesNonDictionaryInput(void);

TGTestOutcome TGFlattenChatListTestFolderNamePayloadKeepsTheServersEntities(void);

TGTestOutcome TGFlattenChatListTestTheBadgeCountsWhatTheSettingsSay(void);
TGTestOutcome TGFlattenChatListTestChatCountUpdateFeedsTheBadge(void);

#endif
