#ifndef TG_HOST_TESTS_FLATTEN_PRIVACY_TESTS_H
#define TG_HOST_TESTS_FLATTEN_PRIVACY_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenPrivacyTestReportReasonTypeForEachKnownReason(void);
TGTestOutcome TGFlattenPrivacyTestReportReasonTypeFallsBackForUnknownReason(void);
TGTestOutcome TGFlattenPrivacyTestReportReasonTypeFallsBackForEmptyOrNilReason(void);
TGTestOutcome TGFlattenPrivacyTestRuleIsModelledForModelledRule(void);
TGTestOutcome TGFlattenPrivacyTestRuleIsModelledForUnmodelledRule(void);
TGTestOutcome TGFlattenPrivacyTestExceptionListRemovingRemovesConflictingIds(void);
TGTestOutcome TGFlattenPrivacyTestExceptionListRemovingPreservesOrderWhenNoConflict(void);
TGTestOutcome TGFlattenPrivacyTestExceptionListRemovingHandlesNilOrEmptyInputsSafely(void);
TGTestOutcome TGFlattenPrivacyTestRuleDictForTypeReturnsNilWhenValueIsEmpty(void);
TGTestOutcome TGFlattenPrivacyTestRuleDictForTypeReturnsRuleWhenValueIsPresent(void);
TGTestOutcome TGFlattenPrivacyTestRebuiltRulesPreservesExistingAllowBeforeRestrictOrder(void);
TGTestOutcome TGFlattenPrivacyTestRebuiltRulesAppendsNewCategoriesInCanonicalOrder(void);
TGTestOutcome TGFlattenPrivacyTestRebuiltRulesPreservesUnmodelledRuleInPlace(void);
TGTestOutcome TGFlattenPrivacyTestRebuiltRulesDropsCategoryWhenNowEmpty(void);
TGTestOutcome TGFlattenPrivacyTestRebuiltRulesAlwaysEndsWithBaseRule(void);
TGTestOutcome TGFlattenPrivacyTestSettingSupportsExceptionsFalseForFindingByPhoneNumber(void);
TGTestOutcome TGFlattenPrivacyTestSettingSupportsExceptionsTrueForOtherSettings(void);

#endif
