#ifndef TG_HOST_TESTS_FLATTEN_APP_SETTINGS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_APP_SETTINGS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenAppSettingsTestApplyFillAndFillFromRowRoundTripSolid(void);
TGTestOutcome TGFlattenAppSettingsTestApplyFillAndFillFromRowRoundTripGradient(void);
TGTestOutcome TGFlattenAppSettingsTestApplyFillAndFillFromRowRoundTripFreeformGradient(void);
TGTestOutcome TGFlattenAppSettingsTestFillFromRowNormalizesAngleAtBoundaries(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundRowClassifiesWallpaperKind(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundRowClassifiesPatternKind(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundRowClassifiesFillKind(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundRowClassifiesThemeKind(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundRowReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundTypeForKindReturnsPatternType(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundTypeForKindReturnsFillType(void);
TGTestOutcome TGFlattenAppSettingsTestBackgroundTypeForKindFallsBackToWallpaperType(void);
TGTestOutcome TGFlattenAppSettingsTestWebDomainExceptionsParsesRealisticList(void);
TGTestOutcome TGFlattenAppSettingsTestWebDomainExceptionsReturnsEmptyForEmptyInput(void);
TGTestOutcome TGFlattenAppSettingsTestThemeColoursFromSettingsExtractsAccentAndOutgoingFill(void);
TGTestOutcome TGFlattenAppSettingsTestThemeColoursFromSettingsIgnoresGradientBottomColour(void);
TGTestOutcome TGFlattenAppSettingsTestThemeColoursFromSettingsReturnsNilWithoutUsableFields(void);

#endif
