#ifndef TG_HOST_TESTS_FLATTEN_ACCOUNT_TESTS_H
#define TG_HOST_TESTS_FLATTEN_ACCOUNT_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForTelegramMessage(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForSms(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForCall(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForMissedCall(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForFlashCall(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForFragment(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleForFirebase(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleFallsBackForUnknownType(void);
TGTestOutcome TGFlattenAccountTestCodeDescriptionAndNextTitleFallsBackForNilType(void);
TGTestOutcome TGFlattenAccountTestCodeInfoDictComposesRealisticPayload(void);
TGTestOutcome TGFlattenAccountTestCodeInfoDictReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenAccountTestEmailCodeInfoComposesPatternAndLength(void);
TGTestOutcome TGFlattenAccountTestEmailCodeInfoReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenAccountTestSessionDictKeepsIdWhenTdlibSendsItAsAString(void);
TGTestOutcome TGFlattenAccountTestSessionDictKeepsIdWhenTdlibSendsItAsANumber(void);
TGTestOutcome TGFlattenAccountTestSessionDictCarriesPasswordPendingAndUnconfirmedFlags(void);
TGTestOutcome TGFlattenAccountTestSessionDictReturnsNilForNonDictionaryInput(void);

#endif
