#ifndef TG_HOST_TESTS_CHAT_POSITION_KEY_TESTS_H
#define TG_HOST_TESTS_CHAT_POSITION_KEY_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGChatPositionKeyTestSameChatDifferentThreadsProduceDifferentKeys(void);
TGTestOutcome TGChatPositionKeyTestSameChatAndThreadProduceTheSameKey(void);
TGTestOutcome TGChatPositionKeyTestZeroThreadKeyDiffersFromNonzeroThreadKey(void);

#endif
