#ifndef TG_HOST_TESTS_FLATTEN_FILES_TESTS_H
#define TG_HOST_TESTS_FLATTEN_FILES_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenFilesTestBase64DecodeValidInput(void);
TGTestOutcome TGFlattenFilesTestBase64DecodeEmptyInput(void);
TGTestOutcome TGFlattenFilesTestBase64DecodeMalformedInput(void);
TGTestOutcome TGFlattenFilesTestFileInfoComposesRealisticPayload(void);
TGTestOutcome TGFlattenFilesTestFileInfoFillsDefaultsForMissingFields(void);
TGTestOutcome TGFlattenFilesTestFileInfoReturnsNilForInvalidInput(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentForDocument(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentForVideo(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentForPhotoPicksLastSize(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentForLivePhotoPrefersMatchingVideoFile(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentForVoiceNote(void);
TGTestOutcome TGFlattenFilesTestFileOfMessageContentFallsBackToNilForUnhandledKind(void);
TGTestOutcome TGFlattenFilesTestBestPhotoSizeInSizesForWidthScalePicksSmallestSizeAtOrAboveWanted(void);
TGTestOutcome TGFlattenFilesTestBestPhotoSizeInSizesForWidthScaleFallsBackToLargestWhenNoneAreBigEnough(void);
TGTestOutcome TGFlattenFilesTestBestPhotoSizeInSizesForWidthScaleHandlesEmptyArray(void);
TGTestOutcome TGFlattenFilesTestBestPhotoSizeInSizesForWidthScaleHandlesSingleEntry(void);
TGTestOutcome TGFlattenFilesTestDecodableThumbnailAcceptsJpegAndPng(void);
TGTestOutcome TGFlattenFilesTestDecodableThumbnailRejectsUnsupportedFormat(void);
TGTestOutcome TGFlattenFilesTestDecodableThumbnailReturnsNilForMissingFile(void);

#endif
