#ifndef TG_HOST_TESTS_FLATTEN_STORAGE_TESTS_H
#define TG_HOST_TESTS_FLATTEN_STORAGE_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenStorageTestNetworkTypeNameRoundTripsWifi(void);
TGTestOutcome TGFlattenStorageTestNetworkTypeNameRoundTripsMobile(void);
TGTestOutcome TGFlattenStorageTestNetworkTypeNameRoundTripsRoaming(void);
TGTestOutcome TGFlattenStorageTestNetworkTypeNameRoundTripsNone(void);
TGTestOutcome TGFlattenStorageTestNetworkTypeNameFallsBackForUnknownOrNil(void);
TGTestOutcome TGFlattenStorageTestFreedBytesAggregatesNestedArray(void);
TGTestOutcome TGFlattenStorageTestFreedBytesReturnsZeroForEmptyArray(void);
TGTestOutcome TGFlattenStorageTestSizesByFileTypeSumsAcrossChats(void);
TGTestOutcome TGFlattenStorageTestSizesByFileTypeMatchesRegardlessOfChatGrouping(void);
TGTestOutcome TGFlattenStorageTestNormalizedAutoDownloadFillsDefaultsForEmptyInput(void);
TGTestOutcome TGFlattenStorageTestNormalizedAutoDownloadPreservesPartialInput(void);
TGTestOutcome TGFlattenStorageTestAutoDownloadFromPresetFillsDefaultsForEmptyInput(void);
TGTestOutcome TGFlattenStorageTestAutoDownloadFromPresetMapsFullInput(void);
TGTestOutcome TGFlattenStorageTestNetworkTypeNameFoldsCaseAndAliases(void);

#endif
