#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="$repo_root/build/host-tests"
binary_path="$build_dir/run-host-tests"
host_test_shim_dir="$repo_root/tests/support/host_shim"

mkdir -p "$build_dir"

pure_app_sources=(
	"$repo_root/src/Model/TGChatComposerState.m"
	"$repo_root/src/Layout/TGChatMessageLayout.m"
	"$repo_root/src/Layout/TGMessageLayout.m"
	"$repo_root/src/Wire/Flatten/TGFlattenMessage.m"
	"$repo_root/src/Wire/Flatten/TGServiceSharedLine.m"
	"$repo_root/src/Wire/Flatten/TGDisappearingMedia.m"
	"$repo_root/src/Wire/Flatten/TGUserDisplayName.m"
	"$repo_root/src/Wire/Flatten/TGPushExtraLine.m"
	"$repo_root/src/Wire/Flatten/TGServiceNotificationAlert.m"
	"$repo_root/src/App/TGLaunchScreenChoice.m"
	"$repo_root/src/Screens/Chat/TGChatHistoryMerge.m"
	"$repo_root/src/Screens/Profile/TGBoosterPageMerge.m"
	"$repo_root/src/Screens/Profile/TGJoinedMemberPageMerge.m"
	"$repo_root/src/Screens/Stickers/TGOwnedSetPageMerge.m"
	"$repo_root/src/Utilities/TGPlainEmojiText.m"
	"$repo_root/src/Utilities/TGSingleLinePreview.m"
	"$repo_root/src/TDLibClient/TGInternalLinkUsername.m"
	"$repo_root/src/TDLibClient/TGBase64.m"
	"$repo_root/src/TDLibClient/TGResultIsError.m"
	"$repo_root/src/TDLibClient/TGChatPositions.m"
	"$repo_root/src/Screens/Chat/TGFailedMessageTitle.m"
	"$repo_root/src/Theme/TGSectionHeaderTitle.m"
	"$repo_root/src/Theme/TGListBackground.m"
	"$repo_root/src/Theme/TGGroupedCaption.m"
	"$repo_root/src/Theme/TGTextFieldStyle.m"
	"$repo_root/src/Theme/TGRowColours.m"
	"$repo_root/src/Screens/Stars/TGStarsAction.m"
	"$repo_root/src/Screens/Chat/TGScheduledFooterText.m"
	"$repo_root/src/Screens/Settings/TGCloseFriendsStatus.m"
	"$repo_root/src/Utilities/TGFormSaveState.m"
	"$repo_root/src/Utilities/TGListStateText.m"
	"$repo_root/src/Utilities/TGCountAfterRead.m"
	"$repo_root/src/Screens/Settings/TGPasswordCheckOutcome.m"
	"$repo_root/src/Screens/Calls/TGCallPeerStateText.m"
	"$repo_root/src/Screens/Stickers/TGArchivedCount.m"
	"$repo_root/src/Utilities/TGFloodWaitText.m"
	"$repo_root/src/Screens/Stickers/TGStickerFavouriteAction.m"
	"$repo_root/src/Screens/Settings/TGWallpaperListText.m"
	"$repo_root/src/Screens/Settings/TGLanguageListText.m"
	"$repo_root/src/Screens/Settings/TGExceptionsListText.m"
	"$repo_root/src/TDLibClient/TGFloodWaitMessage.m"
	"$repo_root/src/TDLibClient/TGRedactedRequestForLogging.m"
	"$repo_root/src/TDLibClient/TGDatabaseEncryptionKey.m"
	"$repo_root/src/TDLibClient/TGMessageTopic.m"
	"$repo_root/src/TDLibClient/TGMessageReadSource.m"
	"$repo_root/src/TDLibClient/TGStorageCachePolicyLimits.m"
	"$repo_root/src/Services/TGReachabilityFlagsKind.m"
	"$repo_root/src/Screens/Chat/TGVideoNoteRingResume.m"
	"$repo_root/src/Screens/Chat/TGChatPositionKey.m"
	"$repo_root/src/Screens/Chat/TGAutoDownloadDecision.m"
	"$repo_root/src/Screens/Chat/TGAutosaveDecision.m"
	"$repo_root/src/Screens/Chat/TGWallpaperRevertEligibility.m"
	"$repo_root/src/Screens/Chat/TGChatUpgradeMarkerFilter.m"
	"$repo_root/src/Screens/Chat/TGLinkPreviewFetchDecision.m"
	"$repo_root/src/Screens/Chat/TGLiveLocationMessageIdRemap.m"
	"$repo_root/src/Screens/Chat/TGLiveLocationRehydration.m"
	"$repo_root/src/Screens/Contacts/TGInviteLinkSubscriptionGuard.m"
	"$repo_root/src/Screens/Settings/TGLoginLinkRecognition.m"
	"$repo_root/src/Storage/TGPasscodeLockoutState.m"
	"$repo_root/src/Screens/Settings/TGRecoveryEmailCodeConfirmation.m"
	"$repo_root/src/Screens/Chat/TGSendAsPremiumGuard.m"
	"$repo_root/src/Screens/Chat/TGTranslationResponseStaleness.m"
	"$repo_root/src/Screens/Chat/TGTranslationLanguageCode.m"
	"$repo_root/src/Screens/Stories/TGStoryComposerPrivacyReset.m"
	"$repo_root/src/Screens/Stories/TGStoryPaging.m"
	"$repo_root/src/Screens/Settings/TGBlockedListPaging.m"
	"$repo_root/src/Utilities/TGStorageKindName.m"
	"$repo_root/src/TDLibClient/TGClientSessionRestart.m"
	"$repo_root/src/Views/TGVisibleAlerts.m"
	"$repo_root/src/Screens/Profile/TGProfileDetailRowHeight.m"
	"$repo_root/src/TDLibClient/TGMessageReply.m"
	"$repo_root/src/Views/TGSeenByStatusText.m"
	"$repo_root/src/Wire/Flatten/TGChatListOutgoingState.m"
	"$repo_root/src/Wire/Flatten/TGChatListPreviewAuthor.m"
	"$repo_root/src/Views/TGProfileSectionMetrics.m"
	"$repo_root/src/Theme/TGGroupedMetrics.m"
	"$repo_root/src/Screens/Chat/TGChatTitleMute.m"
	"$repo_root/src/Views/TGChatTitleCredibility.m"
	"$repo_root/src/Views/TGChatTitlePremium.m"
	"$repo_root/src/Views/TGSenderNameColour.m"
	"$repo_root/src/Utilities/TGVCard.m"
	"$repo_root/src/Utilities/TGBusinessOpenState.m"
	"$repo_root/src/Utilities/TGQuickReplyTrigger.m"
	"$repo_root/src/Utilities/TGPaidReactors.m"
	"$repo_root/src/Utilities/TGBotAdminRights.m"
	"$repo_root/src/Utilities/TGStoryAudience.m"
	"$repo_root/src/Screens/Chat/TGBubbleReuseIdentifier.m"
	"$repo_root/src/Screens/Chat/TGQuoteBodyText.m"
	"$repo_root/src/Screens/Chat/TGSelectionActionAvailability.m"
	"$repo_root/src/Utilities/TGFriendlyError.m"
	"$repo_root/src/Utilities/TGDurationText.m"
	"$repo_root/src/Views/TGStickerTabTitle.m"
	"$repo_root/src/Utilities/TGClockMarker.m"
	"$repo_root/src/Wire/Flatten/TGPollUpdateMerge.m"
	"$repo_root/src/Wire/Flatten/TGDownloadsUpdate.m"
	"$repo_root/src/Screens/Stories/TGStoryViewersFooter.m"
	"$repo_root/src/Screens/Calls/TGCallsEmptyText.m"
	"$repo_root/src/Stores/TGChatHistoryCacheFileName.m"
	"$repo_root/src/Utilities/TGDayWindow.m"
	"$repo_root/src/Screens/Media/TGSharedMediaVisibility.m"
	"$repo_root/src/Screens/Stickers/TGStickerSearchFooter.m"
	"$repo_root/src/Screens/Groups/TGMemberPickerStatusText.m"
	"$repo_root/src/Screens/Settings/TGFolderLinksNotice.m"
	"$repo_root/src/Utilities/TGSettingValueText.m"
	"$repo_root/src/Screens/Media/TGInstantViewRemeasure.m"
	"$repo_root/src/Screens/Profile/Cells/TGProfileDetailCellCatalogue.m"
	"$repo_root/src/Screens/Profile/Cells/TGProfileDetailCell.m"
	"$repo_root/src/Screens/Search/Items/TGSearchResultCellCatalogue.m"
	"$repo_root/src/Screens/Search/Items/TGSearchResultItem.m"
	"$repo_root/src/Screens/Search/Items/TGSearchResultItemBuilder.m"
	"$repo_root/src/Screens/Search/TGSearchMessageCell.m"
	"$repo_root/src/Screens/Search/TGSearchResultCell.m"
	"$repo_root/src/Screens/Search/TGSearchRowMetrics.m"
	"$repo_root/src/Theme/TGHexColour.m"
	"$repo_root/src/Screens/Profile/Items/TGProfileDetailItem.m"
	"$repo_root/src/Screens/Profile/Items/TGProfileDetailItemBuilder.m"
	"$repo_root/src/Screens/Chat/TGQuoteEntitySelection.m"
	"$repo_root/src/Screens/Chat/TGPendingRunShift.m"
	"$repo_root/src/Screens/Chat/TGForwardChunking.m"
	"$repo_root/src/Screens/Calls/TGCallEndText.m"
	"$repo_root/src/Utilities/TGRichText.m"
	"$repo_root/src/Screens/Media/TGPlayerClock.m"
	"$repo_root/src/Screens/Chat/TGLiveLocationFix.m"
	"$repo_root/src/Screens/Chat/TGDiceEmoji.m"
	"$repo_root/src/Theme/TGThemeGeometry.m"
	"$repo_root/src/Screens/Chat/TGChecklistTasks.m"
	"$repo_root/src/Screens/Chat/TGChatRowText.m"
	"$repo_root/src/Utilities/TGDateDayDifference.m"
	"$repo_root/src/Screens/Chat/TGSavedMessagesText.m"
	"$repo_root/src/Screens/Settings/TGPrivacyBotsFlags.m"
	"$repo_root/src/Screens/Settings/TGWallpaperRowText.m"
	"$repo_root/src/Screens/Settings/TGWebBrowserExceptionURL.m"
	"$repo_root/src/Wire/Types"/*.m
	"$repo_root/src/Screens/Chat/Items/TGMessageItem.m"
	"$repo_root/src/Screens/Chat/Items/TGMessageItemResolvedInputs.m"
	"$repo_root/src/Screens/Chat/Items/TGMessageItemBuilder.m"
	"$repo_root/src/Screens/Chat/Layout/TGChatLayoutContext.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Generic.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutCache.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Photo.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Album.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Text.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Service.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+File.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Voice.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Sticker.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+AnimatedSticker.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+BareEmoji.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+VideoNote.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Poll.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Checklist.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Call.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Rich.m"
	"$repo_root/src/Screens/Chat/Layout/TGMessageLayoutBuilder+Location.m"
	"$repo_root/src/Layout/TGMosaicLayout.m"
	"$repo_root/src/Utilities/TGPreferenceFlags.m"
	"$repo_root/src/Utilities/TGDevice.m"
	"$repo_root/src/Utilities/TGByteFormat.m"
	"$repo_root/src/Utilities/TGContactName.m"
	"$repo_root/src/Utilities/TGDateUtils.mm"
	"$repo_root/src/Utilities/TGPluralRules.m"
	"$repo_root/src/Utilities/TGMentionTrigger.m"
	"$repo_root/src/Utilities/TGTextSelectionWordRange.m"
	"$repo_root/src/Utilities/TGStringTruncation.m"
	"$repo_root/src/Wire/Flatten/TGFlattenStory.m"
	"$repo_root/src/Wire/Flatten/TGFlattenWebLinks.m"
	"$repo_root/src/Wire/Flatten/TGFlattenChatManagement.m"
	"$repo_root/src/Wire/Flatten/TGFlattenAccount.m"
	"$repo_root/src/Wire/Flatten/TGFlattenCalls.m"
	"$repo_root/src/Screens/Chat/TGTopicMuteText.m"
	"$repo_root/src/Screens/Chat/TGLiveLocationExpiry.m"
	"$repo_root/src/Screens/Chat/TGBurnLabelLine.m"
	"$repo_root/src/Screens/Groups/TGOwnershipTransferWaitText.m"
	"$repo_root/src/Screens/Groups/TGMembersStatusText.m"
	"$repo_root/src/Screens/Profile/TGProfileAutoDeleteSubtitle.m"
	"$repo_root/src/Screens/Settings/TGProxyLinkInText.m"
	"$repo_root/src/Wire/Flatten/TGFlattenBusiness.m"
	"$repo_root/src/Wire/Flatten/TGFlattenAppSettings.m"
	"$repo_root/src/Wire/Flatten/TGFlattenNetwork.m"
	"$repo_root/src/Wire/Flatten/TGFlattenStickers.m"
	"$repo_root/src/Wire/Flatten/TGFlattenPremium.m"
	"$repo_root/src/Wire/Flatten/TGFlattenMessages.m"
	"$repo_root/src/Wire/Flatten/TGFlattenUserStatus.m"
	"$repo_root/src/Wire/Flatten/TGFlattenContacts.m"
	"$repo_root/src/Wire/Flatten/TGFlattenPayments.m"
	"$repo_root/src/Wire/Flatten/TGFlattenStorage.m"
	"$repo_root/src/Wire/Flatten/TGFlattenSearch.m"
	"$repo_root/src/Wire/Flatten/TGFlattenChannels.m"
	"$repo_root/src/Wire/Flatten/TGFlattenPrivacy.m"
	"$repo_root/src/Wire/Flatten/TGFlattenChatList.m"
	"$repo_root/src/Wire/Flatten/TGFlattenHistory.m"
	"$repo_root/src/Wire/Flatten/TGFlattenGifs.m"
	"$repo_root/src/Wire/Flatten/TGFlattenSecretChats.m"
	"$repo_root/src/Wire/Flatten/TGFlattenReactions.m"
	"$repo_root/src/Wire/Flatten/TGFlattenBots.m"
	"$repo_root/src/Utilities/TGPhoneFormat.m"
	"$repo_root/src/Wire/Flatten/TGFlattenNotifications.m"
	"$repo_root/src/Wire/Flatten/TGFlattenMessageContent.m"
	"$repo_root/src/Wire/Flatten/TGFlattenForums.m"
	"$repo_root/src/Wire/Flatten/TGFlattenSavedMessages.m"
	"$repo_root/src/Wire/Flatten/TGFlattenDirectMessages.m"
	"$repo_root/src/Wire/Flatten/TGFlattenChatState.m"
	"$repo_root/src/Wire/Flatten/TGFlattenFiles.m"
	"$repo_root/src/Wire/Flatten/TGFlattenGroups.m"
	"$repo_root/src/Wire/Flatten/TGFlattenTranslation.m"
	"$repo_root/src/Calls/TGCallMessages.m"
	"$repo_root/src/Calls/TGCallStun.m"
	"$repo_root/src/Stores/TGChatHistoryCache.m"
	"$repo_root/src/Storage/TGDiskCache.m"
	"$repo_root/src/Storage/TGAccountManager.m"
	"$repo_root/src/Utilities/TGChatActionPhraseComposer.m"
	"$repo_root/src/Companions/TGStoryHelpers.m"
	"$repo_root/src/TDLibClient/TGAuthErrorMessage.m"
	"$repo_root/src/Screens/Calls/TGCallsRowText.m"
	"$repo_root/src/Screens/Calls/TGCallListCell.m"
	"$repo_root/src/Screens/Calls/Items/TGCallsItem.m"
	"$repo_root/src/Screens/Calls/Items/TGCallsItemBuilder.m"
	"$repo_root/src/Screens/Groups/Items/TGGroupMembersItem.m"
	"$repo_root/src/Screens/Groups/Items/TGGroupMembersItemBuilder.m"
	"$repo_root/src/Screens/Groups/Items/TGNewGroupMembersItem.m"
	"$repo_root/src/Screens/Groups/Items/TGNewGroupMembersItemBuilder.m"
	"$repo_root/src/Screens/Groups/Items/TGSupergroupUsernamesItem.m"
	"$repo_root/src/Screens/Groups/Items/TGSupergroupUsernamesItemBuilder.m"
	"$repo_root/src/Screens/Settings/Items/TGAccountUsernamesItem.m"
	"$repo_root/src/Screens/Settings/Items/TGAccountUsernamesItemBuilder.m"
	"$repo_root/src/Screens/Settings/Items/TGConnectedWebsitesItem.m"
	"$repo_root/src/Screens/Settings/Items/TGConnectedWebsitesItemBuilder.m"
	"$repo_root/src/Screens/Settings/Items/TGHiddenStoriesItem.m"
	"$repo_root/src/Screens/Settings/Items/TGHiddenStoriesItemBuilder.m"
	"$repo_root/src/Screens/Settings/Items/TGPrivacyContactPickerItem.m"
	"$repo_root/src/Screens/Settings/Items/TGPrivacyContactPickerItemBuilder.m"
	"$repo_root/src/Screens/Stars/Items/TGStarsListItem.m"
	"$repo_root/src/Screens/Stars/Items/TGStarsListItemBuilder.m"
	"$repo_root/src/Screens/Stickers/Items/TGOwnedSetsItem.m"
	"$repo_root/src/Screens/Stickers/Items/TGOwnedSetsItemBuilder.m"
	"$repo_root/src/Screens/Storage/Items/TGStorageDownloadsItem.m"
	"$repo_root/src/Screens/Storage/Items/TGStorageDownloadsItemBuilder.m"
	"$repo_root/src/Screens/Stories/Items/TGStoryViewersItem.m"
	"$repo_root/src/Screens/Stories/Items/TGStoryViewersItemBuilder.m"
)

openssl_include_dir=""
openssl_lib_dir=""
if command -v brew >/dev/null 2>&1 && openssl_brew_prefix="$(brew --prefix openssl@3 2>/dev/null)" && [ -n "$openssl_brew_prefix" ]; then
	openssl_include_dir="$openssl_brew_prefix/include"
	openssl_lib_dir="$openssl_brew_prefix/lib"
elif command -v brew >/dev/null 2>&1 && openssl_brew_prefix="$(brew --prefix openssl@1.1 2>/dev/null)" && [ -n "$openssl_brew_prefix" ]; then
	openssl_include_dir="$openssl_brew_prefix/include"
	openssl_lib_dir="$openssl_brew_prefix/lib"
elif command -v brew >/dev/null 2>&1 && openssl_brew_prefix="$(brew --prefix openssl 2>/dev/null)" && [ -n "$openssl_brew_prefix" ]; then
	openssl_include_dir="$openssl_brew_prefix/include"
	openssl_lib_dir="$openssl_brew_prefix/lib"
elif [ -d /opt/homebrew/opt/openssl@3 ]; then
	openssl_include_dir="/opt/homebrew/opt/openssl@3/include"
	openssl_lib_dir="/opt/homebrew/opt/openssl@3/lib"
elif [ -d /usr/local/opt/openssl@3 ]; then
	openssl_include_dir="/usr/local/opt/openssl@3/include"
	openssl_lib_dir="/usr/local/opt/openssl@3/lib"
fi

if [ -z "$openssl_include_dir" ]; then
	echo "run-host-tests: no host OpenSSL install found (checked Homebrew openssl@3, openssl@1.1, openssl); TGCallStun needs it for HMAC-SHA1" >&2
	exit 1
fi

host_test_sources=(
	"$repo_root/tests/support/host_shim/UIKit/UIKit.m"
	"$repo_root/tests/support/host_stubs.m"
	"$repo_root/tests/support/host_item_catalogue_stubs.m"
	"$repo_root/tests/support/tg_flatten_message_fixture.m"
	"$repo_root/tests/layout/tg_chat_message_layout_tests.m"
	"$repo_root/tests/layout_builder/tg_layout_builder_tests.m"
	"$repo_root/tests/flatten_message/tg_flatten_message_tests.m"
	"$repo_root/tests/chat_upgrade_marker_filter/tg_chat_upgrade_marker_filter_tests.m"
	"$repo_root/tests/mosaic_layout/tg_mosaic_layout_tests.m"
	"$repo_root/tests/utilities/tg_byte_format_tests.m"
	"$repo_root/tests/utilities/tg_contact_name_tests.m"
	"$repo_root/tests/utilities/tg_mention_trigger_tests.m"
	"$repo_root/tests/utilities/tg_text_selection_word_range_tests.m"
	"$repo_root/tests/string_truncation/tg_string_truncation_tests.m"
	"$repo_root/tests/sticker_tab_title/tg_sticker_tab_title_tests.m"
	"$repo_root/tests/clock_marker/tg_clock_marker_tests.m"
	"$repo_root/tests/poll_update_merge/tg_poll_update_merge_tests.m"
	"$repo_root/tests/downloads_update/tg_downloads_update_tests.m"
	"$repo_root/tests/story_viewers_footer/tg_story_viewers_footer_tests.m"
	"$repo_root/tests/calls_empty_text/tg_calls_empty_text_tests.m"
	"$repo_root/tests/chat_history_cache_scope/tg_chat_history_cache_scope_tests.m"
	"$repo_root/tests/day_window/tg_day_window_tests.m"
	"$repo_root/tests/shared_media_visibility/tg_shared_media_visibility_tests.m"
	"$repo_root/tests/message_disappears/tg_message_disappears_tests.m"
	"$repo_root/tests/sticker_search_footer/tg_sticker_search_footer_tests.m"
	"$repo_root/tests/member_picker_status/tg_member_picker_status_tests.m"
	"$repo_root/tests/folder_links_notice/tg_folder_links_notice_tests.m"
	"$repo_root/tests/setting_value_text/tg_setting_value_text_tests.m"
	"$repo_root/tests/chat_positions/tg_chat_positions_tests.m"
	"$repo_root/tests/failed_message_title/tg_failed_message_title_tests.m"
	"$repo_root/tests/section_header_title/tg_section_header_title_tests.m"
	"$repo_root/tests/grouped_list_background/tg_grouped_list_background_tests.m"
	"$repo_root/tests/grouped_caption/tg_grouped_caption_tests.m"
	"$repo_root/tests/action_row/tg_action_row_tests.m"
	"$repo_root/tests/text_field_style/tg_text_field_style_tests.m"
	"$repo_root/tests/row_colours/tg_row_colours_tests.m"
	"$repo_root/tests/stars_action/tg_stars_action_tests.m"
	"$repo_root/tests/scheduled_footer/tg_scheduled_footer_tests.m"
	"$repo_root/tests/close_friends_status/tg_close_friends_status_tests.m"
	"$repo_root/tests/form_save_state/tg_form_save_state_tests.m"
	"$repo_root/tests/wallpaper_list_text/tg_wallpaper_list_text_tests.m"
	"$repo_root/tests/language_list_text/tg_language_list_text_tests.m"
	"$repo_root/tests/exceptions_list_text/tg_exceptions_list_text_tests.m"
	"$repo_root/tests/list_state_text/tg_list_state_text_tests.m"
	"$repo_root/tests/sticker_favourite_action/tg_sticker_favourite_action_tests.m"
	"$repo_root/tests/count_after_read/tg_count_after_read_tests.m"
	"$repo_root/tests/password_check_outcome/tg_password_check_outcome_tests.m"
	"$repo_root/tests/call_peer_state/tg_call_peer_state_tests.m"
	"$repo_root/tests/device_table/tg_device_table_tests.m"
	"$repo_root/tests/archived_count/tg_archived_count_tests.m"
	"$repo_root/tests/flood_wait_notice/tg_flood_wait_notice_tests.m"
	"$repo_root/tests/call_end_text/tg_call_end_text_tests.m"
	"$repo_root/tests/rich_text/tg_rich_text_tests.m"
	"$repo_root/tests/pure_helpers/tg_pure_helpers_tests.m"
	"$repo_root/tests/checklist_tasks/tg_checklist_tasks_tests.m"
	"$repo_root/tests/chat_row_text/tg_chat_row_text_tests.m"
	"$repo_root/tests/date_day_difference/tg_date_day_difference_tests.m"
	"$repo_root/tests/saved_messages_text/tg_saved_messages_text_tests.m"
	"$repo_root/tests/privacy_bots_flags/tg_privacy_bots_flags_tests.m"
	"$repo_root/tests/wallpaper_row_text/tg_wallpaper_row_text_tests.m"
	"$repo_root/tests/item_builders/tg_item_builders_tests.m"
	"$repo_root/tests/story_helpers/tg_story_helpers_tests.m"
	"$repo_root/tests/story_paging/tg_story_paging_tests.m"
	"$repo_root/tests/blocked_list_paging/tg_blocked_list_paging_tests.m"
	"$repo_root/tests/chat_badge_slots/tg_chat_badge_slots_tests.m"
	"$repo_root/tests/frame_time_window/tg_frame_time_window_tests.m"
	"$repo_root/tests/contact_photo_match/tg_contact_photo_match_tests.m"
	"$repo_root/tests/contact_row_measurement/tg_contact_row_measurement_tests.m"
	"$repo_root/tests/avatar_row_key/tg_avatar_row_key_tests.m"
	"$repo_root/tests/table_reload_coalescer/tg_table_reload_coalescer_tests.m"
	"$repo_root/tests/cache_trim/tg_cache_trim_tests.m"
	"$repo_root/tests/mirrored_rect/tg_mirrored_rect_tests.m"
	"$repo_root/tests/chat_date_kind/tg_chat_date_kind_tests.m"
	"$repo_root/tests/rights_diff/tg_rights_diff_tests.m"
	"$repo_root/tests/privacy_setting_title/tg_privacy_setting_title_tests.m"
	"$repo_root/tests/search_author_line/tg_search_author_line_tests.m"
	"$repo_root/tests/calls_reload_policy/tg_calls_reload_policy_tests.m"
	"$repo_root/tests/list_load_failure/tg_list_load_failure_tests.m"
	"$repo_root/tests/request_expiry/tg_request_expiry_tests.m"
	"$repo_root/tests/media_preview_name/tg_media_preview_name_tests.m"
	"$repo_root/tests/tdlib_int64/tg_tdlib_int64_tests.m"
	"$repo_root/tests/service_shared_line/tg_service_shared_line_tests.m"
	"$repo_root/tests/push_extra_line/tg_push_extra_line_tests.m"
	"$repo_root/tests/service_notification_alert/tg_service_notification_alert_tests.m"
	"$repo_root/tests/chat_title_credibility/tg_chat_title_credibility_tests.m"
	"$repo_root/tests/chat_title_premium/tg_chat_title_premium_tests.m"
	"$repo_root/tests/sender_name_colour/tg_sender_name_colour_tests.m"
	"$repo_root/tests/vcard/tg_vcard_tests.m"
	"$repo_root/tests/paid_reactors/tg_paid_reactors_tests.m"
	"$repo_root/tests/bot_admin_rights/tg_bot_admin_rights_tests.m"
	"$repo_root/tests/story_audience/tg_story_audience_tests.m"
	"$repo_root/tests/business_open_state/tg_business_open_state_tests.m"
	"$repo_root/tests/quick_reply_trigger/tg_quick_reply_trigger_tests.m"
	"$repo_root/tests/bubble_reuse_identifier/tg_bubble_reuse_identifier_tests.m"
	"$repo_root/tests/quote_body_text/tg_quote_body_text_tests.m"
	"$repo_root/tests/disappearing_media/tg_disappearing_media_tests.m"
	"$repo_root/tests/user_display_name/tg_user_display_name_tests.m"
	"$repo_root/tests/selection_action_availability/tg_selection_action_availability_tests.m"
	"$repo_root/tests/friendly_error/tg_friendly_error_tests.m"
	"$repo_root/tests/duration_text/tg_duration_text_tests.m"
	"$repo_root/tests/list_status/tg_list_status_tests.m"
	"$repo_root/src/Wire/Flatten/TGMediaPreviewName.m"
	"$repo_root/src/TDLibClient/TGRequestExpiry.m"
	"$repo_root/src/Utilities/TGListLoadFailure.m"
	"$repo_root/src/Screens/Calls/TGCallsReloadPolicy.m"
	"$repo_root/src/Screens/Search/TGSearchAuthorLine.m"
	"$repo_root/src/Utilities/TGPrivacySettingTitle.m"
	"$repo_root/src/TDLibClient/TGRightsDiff.m"
	"$repo_root/tests/chat_swipe_actions/tg_chat_swipe_actions_tests.m"
	"$repo_root/tests/chat_preview_kind/tg_chat_preview_kind_tests.m"
	"$repo_root/src/Screens/ChatList/TGChatPreviewKind.m"
	"$repo_root/tests/search_bar_pin/tg_search_bar_pin_tests.m"
	"$repo_root/tests/unread_summary_key/tg_unread_summary_key_tests.m"
	"$repo_root/src/Screens/ChatList/TGUnreadSummaryKey.m"
	"$repo_root/src/Screens/ChatList/TGSearchBarPin.m"
	"$repo_root/src/Screens/ChatList/TGChatSwipeActions.m"
	"$repo_root/src/Screens/ChatList/TGChatDateKind.m"
	"$repo_root/src/Utilities/TGMirroredRect.m"
	"$repo_root/tests/folder_chat_count/tg_folder_chat_count_tests.m"
	"$repo_root/src/Screens/Settings/TGFolderChatCount.m"
	"$repo_root/tests/message_layout_cache/tg_message_layout_cache_tests.m"
	"$repo_root/src/Utilities/TGCacheTrim.m"
	"$repo_root/src/Views/TGTableReloadCoalescer.m"
	"$repo_root/src/Companions/TGAvatarRowKey.m"
	"$repo_root/src/Screens/Contacts/Cells/TGContactRowMeasurement.m"
	"$repo_root/src/Screens/Contacts/TGContactPhotoMatch.m"
	"$repo_root/src/Utilities/TGFrameTimeWindow.m"
	"$repo_root/src/Screens/ChatList/TGChatBadgeSlots.m"
	"$repo_root/tests/saved_mode_sheet_action/tg_saved_mode_sheet_action_tests.m"
	"$repo_root/src/Screens/Chat/TGSavedModeSheetAction.m"
	"$repo_root/tests/storage_chat_titles/tg_storage_chat_titles_tests.m"
	"$repo_root/tests/storage_kind_name/tg_storage_kind_name_tests.m"
	"$repo_root/tests/session_restart/tg_session_restart_tests.m"
	"$repo_root/tests/visible_alerts/tg_visible_alerts_tests.m"
	"$repo_root/tests/profile_detail_row_height/tg_profile_detail_row_height_tests.m"
	"$repo_root/tests/message_reply/tg_message_reply_tests.m"
	"$repo_root/tests/seen_by_status/tg_seen_by_status_tests.m"
	"$repo_root/tests/chat_list_outgoing_state/tg_chat_list_outgoing_state_tests.m"
	"$repo_root/tests/chat_list_preview_author/tg_chat_list_preview_author_tests.m"
	"$repo_root/tests/profile_section_metrics/tg_profile_section_metrics_tests.m"
	"$repo_root/tests/grouped_metrics/tg_grouped_metrics_tests.m"
	"$repo_root/tests/chat_title_mute/tg_chat_title_mute_tests.m"
	"$repo_root/tests/instant_view_remeasure/tg_instant_view_remeasure_tests.m"
	"$repo_root/tests/calls_row/tg_calls_row_tests.m"
	"$repo_root/tests/base64/tg_base64_tests.m"
	"$repo_root/tests/auth_error_message/tg_auth_error_message_tests.m"
	"$repo_root/tests/launch_screen_choice/tg_launch_screen_choice_tests.m"
	"$repo_root/tests/chat_history_merge/tg_chat_history_merge_tests.m"
	"$repo_root/tests/booster_page_merge/tg_booster_page_merge_tests.m"
	"$repo_root/tests/joined_member_page_merge/tg_joined_member_page_merge_tests.m"
	"$repo_root/tests/owned_set_page_merge/tg_owned_set_page_merge_tests.m"
	"$repo_root/tests/preference_flags/tg_preference_flags_tests.m"
	"$repo_root/tests/internal_link_username/tg_internal_link_username_tests.m"
	"$repo_root/tests/plain_emoji_text/tg_plain_emoji_text_tests.m"
	"$repo_root/tests/single_line_preview/tg_single_line_preview_tests.m"
	"$repo_root/tests/date_utils/tg_date_utils_tests.m"
	"$repo_root/tests/plural_rules/tg_plural_rules_tests.m"
	"$repo_root/tests/flatten_story/tg_flatten_story_tests.m"
	"$repo_root/tests/flatten_weblinks/tg_flatten_weblinks_tests.m"
	"$repo_root/tests/flatten_chat_management/tg_flatten_chat_management_tests.m"
	"$repo_root/tests/flatten_account/tg_flatten_account_tests.m"
	"$repo_root/tests/flatten_calls/tg_flatten_calls_tests.m"
	"$repo_root/tests/topic_mute_text/tg_topic_mute_text_tests.m"
	"$repo_root/tests/ownership_transfer_wait_text/tg_ownership_transfer_wait_text_tests.m"
	"$repo_root/tests/members_status_text/tg_members_status_text_tests.m"
	"$repo_root/tests/profile_auto_delete_subtitle/tg_profile_auto_delete_subtitle_tests.m"
	"$repo_root/tests/live_location/tg_live_location_expiry_tests.m"
	"$repo_root/tests/live_location_rehydration/tg_live_location_rehydration_tests.m"
	"$repo_root/tests/burn_label_line/tg_burn_label_line_tests.m"
	"$repo_root/tests/flatten_business/tg_flatten_business_tests.m"
	"$repo_root/tests/flatten_app_settings/tg_flatten_app_settings_tests.m"
	"$repo_root/tests/flatten_network/tg_flatten_network_tests.m"
	"$repo_root/tests/flatten_stickers/tg_flatten_stickers_tests.m"
	"$repo_root/tests/flatten_premium/tg_flatten_premium_tests.m"
	"$repo_root/tests/flatten_messages/tg_flatten_messages_tests.m"
	"$repo_root/tests/flatten_user_status/tg_flatten_user_status_tests.m"
	"$repo_root/tests/flatten_contacts/tg_flatten_contacts_tests.m"
	"$repo_root/tests/flatten_payments/tg_flatten_payments_tests.m"
	"$repo_root/tests/flatten_storage/tg_flatten_storage_tests.m"
	"$repo_root/tests/flatten_search/tg_flatten_search_tests.m"
	"$repo_root/tests/flatten_channels/tg_flatten_channels_tests.m"
	"$repo_root/tests/flatten_privacy/tg_flatten_privacy_tests.m"
	"$repo_root/tests/flatten_chat_list/tg_flatten_chat_list_tests.m"
	"$repo_root/tests/flatten_history/tg_flatten_history_tests.m"
	"$repo_root/tests/flatten_gifs/tg_flatten_gifs_tests.m"
	"$repo_root/tests/flatten_secret_chats/tg_flatten_secret_chats_tests.m"
	"$repo_root/tests/flatten_reactions/tg_flatten_reactions_tests.m"
	"$repo_root/tests/flatten_bots/tg_flatten_bots_tests.m"
	"$repo_root/tests/phone_strip/tg_phone_strip_tests.m"
	"$repo_root/tests/flatten_notifications/tg_flatten_notifications_tests.m"
	"$repo_root/tests/flatten_message_content/tg_flatten_message_content_tests.m"
	"$repo_root/tests/flatten_forums/tg_flatten_forums_tests.m"
	"$repo_root/tests/flatten_saved_messages/tg_flatten_saved_messages_tests.m"
	"$repo_root/tests/flatten_direct_messages/tg_flatten_direct_messages_tests.m"
	"$repo_root/tests/flatten_chat_state/tg_flatten_chat_state_tests.m"
	"$repo_root/tests/flatten_files/tg_flatten_files_tests.m"
	"$repo_root/tests/flatten_groups/tg_flatten_groups_tests.m"
	"$repo_root/tests/flatten_translation/tg_flatten_translation_tests.m"
	"$repo_root/tests/call_messages/tg_call_messages_tests.m"
	"$repo_root/tests/call_stun/tg_call_stun_tests.m"
	"$repo_root/tests/chat_history_cache/tg_chat_history_cache_tests.m"
	"$repo_root/tests/disk_cache/tg_disk_cache_tests.m"
	"$repo_root/tests/database_encryption_key/tg_database_encryption_key_tests.m"
	"$repo_root/tests/support/tg_client_test_double.m"
	"$repo_root/tests/account_manager/tg_account_manager_tests.m"
	"$repo_root/tests/reachability/tg_reachability_tests.m"
	"$repo_root/tests/auto_download/tg_auto_download_tests.m"
	"$repo_root/tests/autosave/tg_autosave_tests.m"
	"$repo_root/tests/video_note_ring_resume/tg_video_note_ring_resume_tests.m"
	"$repo_root/tests/composer_state/tg_composer_state_tests.m"
	"$repo_root/tests/quote_entity_selection/tg_quote_entity_selection_tests.m"
	"$repo_root/tests/pending_run_shift/tg_pending_run_shift_tests.m"
	"$repo_root/tests/forward_chunking/tg_forward_chunking_tests.m"
	"$repo_root/tests/chat_action_phrase/tg_chat_action_phrase_tests.m"
	"$repo_root/tests/redacted_request_logging/tg_redacted_request_logging_tests.m"
	"$repo_root/tests/flood_wait_message/tg_flood_wait_message_tests.m"
	"$repo_root/tests/proxy_link_in_text/tg_proxy_link_in_text_tests.m"
	"$repo_root/tests/message_topic/tg_message_topic_tests.m"
	"$repo_root/tests/message_read_source/tg_message_read_source_tests.m"
	"$repo_root/tests/storage_cache_policy_limits/tg_storage_cache_policy_limits_tests.m"
	"$repo_root/tests/chat_position_key/tg_chat_position_key_tests.m"
	"$repo_root/tests/invite_link_subscription_guard/tg_invite_link_subscription_guard_tests.m"
	"$repo_root/tests/login_link_recognition/tg_login_link_recognition_tests.m"
	"$repo_root/tests/passcode_lockout_state/tg_passcode_lockout_state_tests.m"
	"$repo_root/tests/recovery_email_code_confirmation/tg_recovery_email_code_confirmation_tests.m"
	"$repo_root/tests/send_as_premium_guard/tg_send_as_premium_guard_tests.m"
	"$repo_root/tests/translation_response_staleness/tg_translation_response_staleness_tests.m"
	"$repo_root/tests/translation_language_code/tg_translation_language_code_tests.m"
	"$repo_root/tests/story_composer_privacy_reset/tg_story_composer_privacy_reset_tests.m"
	"$repo_root/tests/wallpaper_revert_eligibility/tg_wallpaper_revert_eligibility_tests.m"
	"$repo_root/tests/live_location_message_id_remap/tg_live_location_message_id_remap_tests.m"
	"$repo_root/tests/link_preview_fetch_decision/tg_link_preview_fetch_decision_tests.m"
	"$repo_root/tests/host_tests_main.m"
)

echo "run-host-tests: compiling ${#pure_app_sources[@]} pure app source file(s) and ${#host_test_sources[@]} test file(s) for the host, no iOS SDK involved"

clang \
	-fobjc-arc \
	-Wall \
	-Wno-unused-parameter \
	-I "$host_test_shim_dir" \
	-I "$host_test_shim_dir/UIKit" \
	-I "$repo_root/src/Layout" \
	-I "$repo_root/src/Theme" \
	-I "$repo_root/src/Utilities" \
	-I "$repo_root/src/Model" \
	-I "$repo_root/src/Views" \
	-I "$repo_root/src/Views/Cells" \
	-I "$repo_root/src/Wire/Types" \
	-I "$repo_root/src/Wire/Flatten" \
	-I "$repo_root/src/Screens/Chat/Items" \
	-I "$repo_root/src/Screens/Chat/Layout" \
	-I "$repo_root/src/Screens/Chat/Cells" \
	-I "$repo_root/src/Screens/Chat" \
	-I "$repo_root/src/Screens/Contacts" \
	-I "$repo_root/src/TDLibClient" \
	-I "$repo_root/src/Calls" \
	-I "$repo_root/src/Stores" \
	-I "$repo_root/src/Storage" \
	-I "$repo_root/src/Services" \
	-I "$repo_root/src/Companions" \
	-I "$repo_root/src/Screens/Calls/Items" \
	-I "$repo_root/src/Screens/Calls" \
	-I "$repo_root/src/Screens/Groups/Items" \
	-I "$repo_root/src/Screens/Groups" \
	-I "$repo_root/src/Media" \
	-I "$repo_root/src/Screens/Groups/Cells" \
	-I "$repo_root/src/Screens/Settings/Items" \
	-I "$repo_root/src/Screens/Settings/Cells" \
	-I "$repo_root/src/Screens/Stars/Items" \
	-I "$repo_root/src/Screens/Stars/Cells" \
	-I "$repo_root/src/Screens/Stickers/Items" \
	-I "$repo_root/src/Screens/Stickers/Cells" \
	-I "$repo_root/src/Screens/Storage/Items" \
	-I "$repo_root/src/Screens/Storage/Cells" \
	-I "$repo_root/src/Screens/Profile/Items" \
	-I "$repo_root/src/Screens/Search/Items" \
	-I "$repo_root/src/Screens/Search" \
	-I "$repo_root/src/Screens/Profile/Cells" \
	-I "$repo_root/src/Screens/Profile" \
	-I "$repo_root/src/Screens/Stories/Items" \
	-I "$repo_root/src/Screens/Stories/Cells" \
	-I "$repo_root/src/Screens/Media" \
	-I "$repo_root/src/Screens/Settings" \
	-I "$repo_root/src/Screens/Storage" \
	-I "$openssl_include_dir" \
	-framework Foundation \
	-framework CoreGraphics \
	-framework CoreText \
	-framework Security \
	-framework SystemConfiguration \
	-lc++ \
	-L "$openssl_lib_dir" \
	-lcrypto \
	-lz \
	"${pure_app_sources[@]}" \
	"${host_test_sources[@]}" \
	-o "$binary_path"

echo "run-host-tests: built $binary_path"
echo "run-host-tests: running"
echo

exec "$binary_path"
