#ifndef TG_HOST_TESTS_MOSAIC_LAYOUT_TESTS_H
#define TG_HOST_TESTS_MOSAIC_LAYOUT_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGMosaicLayoutTestCountTwoLandscapePairStacksTopAndBottom(void);
TGTestOutcome TGMosaicLayoutTestCountTwoSideBySideForWwAndQqProportions(void);
TGTestOutcome TGMosaicLayoutTestCountTwoPortraitPairSplitsEvenly(void);
TGTestOutcome TGMosaicLayoutTestCountTwoMixedRatioPairWeightsWidthByAspect(void);
TGTestOutcome TGMosaicLayoutTestCountThreeNarrowFirstImageMakesTallLeftColumn(void);
TGTestOutcome TGMosaicLayoutTestCountThreeFillWidthForcesExactHalfRightColumn(void);
TGTestOutcome TGMosaicLayoutTestCountThreeGeneralLayoutStacksTwoUnderOne(void);
TGTestOutcome TGMosaicLayoutTestCountFourWideFirstImageMakesFullWidthHeader(void);
TGTestOutcome TGMosaicLayoutTestCountFourNarrowFirstImageMakesTallLeftColumn(void);
TGTestOutcome TGMosaicLayoutTestCountFiveUsesGeneralSolver(void);
TGTestOutcome TGMosaicLayoutTestCountSixUsesGeneralSolver(void);
TGTestOutcome TGMosaicLayoutTestCountTenAtMosaicMaxItemsBoundary(void);
TGTestOutcome TGMosaicLayoutTestForceCalcTriggeredByExtremeWideRatioAtCountThree(void);
TGTestOutcome TGMosaicLayoutTestForceCalcTriggeredForCountTwo(void);
TGTestOutcome TGMosaicLayoutTestDegenerateCountOutsideValidRangeReturnsZero(void);
TGTestOutcome TGMosaicLayoutTestDegenerateMaxSizeBelowOnePointReturnsZero(void);
TGTestOutcome TGMosaicLayoutTestMinTileSizeClampAppliesInThreeAndFourUpBranches(void);
TGTestOutcome TGMosaicLayoutTestInvariantNoNegativeSizesAndTilesFitWithinReturnedTotal(void);

#endif
