#ifndef TG_HOST_TESTS_FLATTEN_MESSAGE_TESTS_H
#define TG_HOST_TESTS_FLATTEN_MESSAGE_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenMessageTestFlattensTextMessage(void);
TGTestOutcome TGFlattenMessageTestFlattensPhotoWithCaption(void);
TGTestOutcome TGFlattenMessageTestFlattensVoiceNoteWaveform(void);
TGTestOutcome TGFlattenMessageTestFlattensVoiceNoteTranscript(void);
TGTestOutcome TGFlattenMessageTestFlattensQuizPollWithCorrectOptionAndExplanation(void);
TGTestOutcome TGFlattenMessageTestPollQuizCorrectOptionIdPicksFirstElement(void);
TGTestOutcome TGFlattenMessageTestPollOptionPercentagesSurviveFlatteningWithoutFloatTruncation(void);
TGTestOutcome TGFlattenMessageTestPollAllowsRevotingRoundTrips(void);
TGTestOutcome TGFlattenMessageTestFlattensDice(void);
TGTestOutcome TGFlattenMessageTestFlattensServiceActions(void);
TGTestOutcome TGFlattenMessageTestPinMessageDescriptorResolvesByContentKind(void);
TGTestOutcome TGFlattenMessageTestFlattensChatSetBackgroundOldMessageId(void);
TGTestOutcome TGFlattenMessageTestSecretChatAutoDeleteServiceMessageUsesSecretWording(void);
TGTestOutcome TGFlattenMessageTestDestructDeadlineTracksWallClockAcrossReopens(void);
TGTestOutcome TGFlattenMessageTestFlattensReactionChips(void);
TGTestOutcome TGFlattenMessageTestFlattensForwardedMessage(void);
TGTestOutcome TGFlattenMessageTestFlattensReplyThatQuotesAnotherMessage(void);
TGTestOutcome TGFlattenMessageTestFlattensReplyFromDiscussionGroupToLinkedChannel(void);
TGTestOutcome TGFlattenMessageTestFlattensReplyToStory(void);
TGTestOutcome TGFlattenMessageTestFlattensExpiredMediaMessage(void);
TGTestOutcome TGFlattenMessageTestFlattensExpiredPhotoMessage(void);
TGTestOutcome TGFlattenMessageTestFlattensChannelPostComments(void);
TGTestOutcome TGFlattenMessageTestFlattensMessageEffectId(void);
TGTestOutcome TGFlattenMessageTestFlattensSlotMachineDice(void);
TGTestOutcome TGFlattenMessageTestFlattensSenderIdentity(void);
TGTestOutcome TGFlattenMessageTestFlattensSchedulingState(void);
TGTestOutcome TGFlattenMessageTestFlattensCaptionAboveMediaAndLinkPreviewOptions(void);
TGTestOutcome TGFlattenMessageTestSendErrorMessageReadsSlowModeFromChatsById(void);
TGTestOutcome TGFlattenMessageTestCallCarriesItsTitleAndDurationApart(void);
TGTestOutcome TGFlattenMessageTestDisappearingMediaSaysSoInTheChatList(void);
TGTestOutcome TGFlattenMessageTestADisappearingCaptionNeverLeavesTheChat(void);
TGTestOutcome TGFlattenMessageTestAReplyNamesEveryKindItCanQuote(void);
TGTestOutcome TGFlattenMessageTestPaidAndUnsupportedKindsAreNamedEverywhere(void);
TGTestOutcome TGFlattenMessageTestTheSharedKindTableNamesWhatEachSurfaceNeeds(void);

#endif
