#ifndef TG_HOST_TESTS_FLATTEN_GROUPS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_GROUPS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenGroupsTestProfileTabNameStripsPrefixAndLowercases(void);
TGTestOutcome TGFlattenGroupsTestProfileTabNameReturnsEmptyForMissingPrefixOrShortOrNilOrNonDictionary(void);

TGTestOutcome TGFlattenGroupsTestUserSenderBuildsMessageSenderUserDict(void);

TGTestOutcome TGFlattenGroupsTestFlattenMemberIdentityReadsUserIdForMessageSenderUser(void);
TGTestOutcome TGFlattenGroupsTestFlattenMemberIdentityReadsChatIdForMessageSenderChat(void);
TGTestOutcome TGFlattenGroupsTestFlattenMemberIdentityDefaultsSafelyForNilOrNonDictionary(void);

TGTestOutcome TGFlattenGroupsTestPermissionKeysContainsExpectedKeysInOrder(void);
TGTestOutcome TGFlattenGroupsTestAdminRightKeysContainsExpectedKeysInOrder(void);

TGTestOutcome TGFlattenGroupsTestBuildFlagsSetsTypeAndReadsEachKeyAsBool(void);
TGTestOutcome TGFlattenGroupsTestBuildFlagsDefaultsMissingSourceKeysToFalse(void);
TGTestOutcome TGFlattenGroupsTestReadFlagsReadsEachKeyAsBoolWithoutType(void);
TGTestOutcome TGFlattenGroupsTestReadFlagsDefaultsMissingSourceKeysToFalse(void);

TGTestOutcome TGFlattenGroupsTestStatusNameMapsAllKnownStatuses(void);
TGTestOutcome TGFlattenGroupsTestStatusNameFallsBackToLeftForUnknownOrEmptyType(void);

TGTestOutcome TGFlattenGroupsTestSupergroupFilterMapsNamedFiltersAndCarriesQueryWhereApplicable(void);
TGTestOutcome TGFlattenGroupsTestSupergroupFilterFallsBackToSearchWhenQueryPresentAndFilterUnknown(void);
TGTestOutcome TGFlattenGroupsTestSupergroupFilterFallsBackToRecentWhenNoQueryAndFilterUnknown(void);

TGTestOutcome TGFlattenGroupsTestChatMembersFilterMapsNamedFilters(void);
TGTestOutcome TGFlattenGroupsTestChatMembersFilterFallsBackToMembersForUnknownFilter(void);

TGTestOutcome TGFlattenGroupsTestFlattenInviteLinkMapsAllFieldsForValidLink(void);
TGTestOutcome TGFlattenGroupsTestFlattenInviteLinkDefaultsMissingNumericAndBooleanFields(void);
TGTestOutcome TGFlattenGroupsTestFlattenInviteLinkReturnsNilForWrongTypeOrNonDictionaryOrNil(void);

TGTestOutcome TGFlattenGroupsTestTitleForAdministratorRightKeyKnownKeysReturnHumanReadableTitles(void);
TGTestOutcome TGFlattenGroupsTestTitleForAdministratorRightKeyUnknownNonEmptyKeyReturnsKeyItself(void);
TGTestOutcome TGFlattenGroupsTestTitleForAdministratorRightKeyNilOrEmptyReturnsEmptyString(void);

TGTestOutcome TGFlattenGroupsTestTitleForMemberPermissionKeyKnownKeysReturnHumanReadableTitles(void);
TGTestOutcome TGFlattenGroupsTestTitleForMemberPermissionKeyUnknownNonEmptyKeyReturnsKeyItself(void);
TGTestOutcome TGFlattenGroupsTestTitleForMemberPermissionKeyNilOrEmptyReturnsEmptyString(void);

TGTestOutcome TGFlattenGroupsTestMentionCandidateJoinsFirstAndLastName(void);
TGTestOutcome TGFlattenGroupsTestMentionCandidateFallsBackToFallbackNameThenUsername(void);
TGTestOutcome TGFlattenGroupsTestMentionCandidateCarriesUserIdAndUsernameRegardlessOfName(void);
TGTestOutcome TGFlattenGroupsTestMemberRestrictionReadsRestrictedAndBannedStatuses(void);
TGTestOutcome TGFlattenGroupsTestMemberRestrictionFallsBackToChatDefaultsForEveryOtherStatus(void);

#endif
