#ifndef TG_HOST_TESTS_FLATTEN_SEARCH_TESTS_H
#define TG_HOST_TESTS_FLATTEN_SEARCH_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenSearchTestTextForContentPrefersMessageText(void);
TGTestOutcome TGFlattenSearchTestTextForContentPrefersNonEmptyCaption(void);
TGTestOutcome TGFlattenSearchTestTextForContentIgnoresEmptyCaption(void);
TGTestOutcome TGFlattenSearchTestTextForContentCoversMediaKindsWithoutCaption(void);
TGTestOutcome TGFlattenSearchTestTextForContentDocumentUsesFileNameOrFallback(void);
TGTestOutcome TGFlattenSearchTestTextForContentAudioUsesTitleOrFallback(void);
TGTestOutcome TGFlattenSearchTestTextForContentFallsBackForUnknownKind(void);
TGTestOutcome TGFlattenSearchTestTextForContentFallsBackForNonDictionaryInput(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentMessagePhotoReturnsLargestSize(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentMessagePhotoReturnsNilWhenNoSizes(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentThumbnailKinds(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentReturnsNilWhenThumbnailMissing(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentReturnsNilForKindWithoutPhotoKey(void);
TGTestOutcome TGFlattenSearchTestPhotoIdForContentReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenSearchTestRowsNameTheKindsTheyCannotQuote(void);

#endif
