#ifndef TG_HOST_TESTS_FLATTEN_PAYMENTS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_PAYMENTS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenPaymentsTestShortTypeStripsKnownPrefix(void);
TGTestOutcome TGFlattenPaymentsTestShortTypeFallsBackWhenPrefixMissing(void);
TGTestOutcome TGFlattenPaymentsTestHumanTypeLooksUpKnownShortTypes(void);
TGTestOutcome TGFlattenPaymentsTestHumanTypeFallsBackForUnknownOrEmptyShortType(void);
TGTestOutcome TGFlattenPaymentsTestShortTypeAndHumanTypeRoundTrip(void);
TGTestOutcome TGFlattenPaymentsTestStarsFromDictionaryRepresentation(void);
TGTestOutcome TGFlattenPaymentsTestStarsFromNumberRepresentation(void);
TGTestOutcome TGFlattenPaymentsTestStarsReturnsZeroForUnrecognisedInput(void);
TGTestOutcome TGFlattenPaymentsTestStarsNanosFromDictionaryRepresentation(void);
TGTestOutcome TGFlattenPaymentsTestStarsNanosReturnsZeroForUnrecognisedInput(void);
TGTestOutcome TGFlattenPaymentsTestPhotoFileIdPicksWidestOfMultipleSizes(void);
TGTestOutcome TGFlattenPaymentsTestPhotoFileIdPicksTheSingleSize(void);
TGTestOutcome TGFlattenPaymentsTestPhotoFileIdReturnsNilForEmptySizes(void);
TGTestOutcome TGFlattenPaymentsTestDecimalAmountDividesMinorUnitsByOneHundred(void);
TGTestOutcome TGFlattenPaymentsTestDecimalAmountKeepsTwoDecimalPlacesForRoundAmounts(void);
TGTestOutcome TGFlattenPaymentsTestDecimalAmountHandlesNegativeAndZeroAmounts(void);
TGTestOutcome TGFlattenPaymentsTestDecimalAmountHonoursPerCurrencyExponent(void);

#endif
