#ifndef TG_HOST_TESTS_FLATTEN_CHANNELS_TESTS_H
#define TG_HOST_TESTS_FLATTEN_CHANNELS_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenChannelsTestGraphFlattensStatisticalGraphData(void);
TGTestOutcome TGFlattenChannelsTestGraphFlattensStatisticalGraphAsync(void);
TGTestOutcome TGFlattenChannelsTestGraphReturnsNilForUnknownTypeOrNonDictionary(void);
TGTestOutcome TGFlattenChannelsTestGraphFlattensStatisticalGraphError(void);
TGTestOutcome TGFlattenChannelsTestValueFlattensRealisticPayload(void);
TGTestOutcome TGFlattenChannelsTestValueReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenChannelsTestAddGraphsCollectsMultipleEntriesAndSkipsMissing(void);
TGTestOutcome TGFlattenChannelsTestAddGraphsHandlesEmptyPairs(void);
TGTestOutcome TGFlattenChannelsTestAddValuesCollectsMultipleEntriesAndSkipsMissing(void);
TGTestOutcome TGFlattenChannelsTestAddValuesHandlesEmptyPairs(void);
TGTestOutcome TGFlattenChannelsTestBoostSlotNeverUsedIsFreeAndAvailable(void);
TGTestOutcome TGFlattenChannelsTestBoostSlotBoostingAnotherChatInCooldownIsCommitted(void);
TGTestOutcome TGFlattenChannelsTestBoostSlotBoostingAnotherChatAfterCooldownIsReassignableNotFree(void);
TGTestOutcome TGFlattenChannelsTestBoostSlotCooldownBoundaryEqualsNowIsAvailable(void);

#endif
