#ifndef TG_HOST_TESTS_LINK_PREVIEW_FETCH_DECISION_TESTS_H
#define TG_HOST_TESTS_LINK_PREVIEW_FETCH_DECISION_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGLinkPreviewFetchDecisionTestEmptyTextIsNotCandidate(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNilTextIsNotCandidate(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestPlainTextIsCandidate(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestBareDomainTextIsCandidate(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNilOptionsAreNotDisabled(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNonDictionaryOptionsAreNotDisabled(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestExplicitIsDisabledTrueIsDisabled(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestExplicitIsDisabledFalseIsNotDisabled(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestMissingIsDisabledKeyIsNotDisabled(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNilOptionsProduceDefaultValues(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNonDictionaryOptionsProduceDefaultValues(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestValuesEchoStoredUrlAndFlags(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestMissingUrlKeyFallsBackToEmptyString(void);
TGTestOutcome TGLinkPreviewFetchDecisionTestNonStringUrlFallsBackToEmptyString(void);

#endif
