#ifndef TG_HOST_TESTS_FLATTEN_NETWORK_TESTS_H
#define TG_HOST_TESTS_FLATTEN_NETWORK_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenNetworkTestNetworkTypeNameMapsKnownKinds(void);
TGTestOutcome TGFlattenNetworkTestNetworkTypeNameFallsBackForUnknownOrNilKind(void);
TGTestOutcome TGFlattenNetworkTestProxyTypeObjectBuildsMtproto(void);
TGTestOutcome TGFlattenNetworkTestProxyTypeObjectBuildsHttp(void);
TGTestOutcome TGFlattenNetworkTestProxyTypeObjectFallsBackToSocks5(void);
TGTestOutcome TGFlattenNetworkTestProxyDictParsesMtprotoFromTDLibObject(void);
TGTestOutcome TGFlattenNetworkTestProxyDictParsesHttpFromTDLibObject(void);
TGTestOutcome TGFlattenNetworkTestProxyDictParsesSocks5FromTDLibObject(void);
TGTestOutcome TGFlattenNetworkTestProxyDictReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenNetworkTestAddedProxyDictMergesAddedFields(void);
TGTestOutcome TGFlattenNetworkTestAddedProxyDictReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenNetworkTestProxyRoundTripsThroughBothDirectionsForEachKind(void);
TGTestOutcome TGFlattenNetworkTestSettingsDictComposesFromTDLibObject(void);
TGTestOutcome TGFlattenNetworkTestSettingsDictReturnsNilForNonDictionaryInput(void);
TGTestOutcome TGFlattenNetworkTestSettingsObjectComposesFromFlatDict(void);
TGTestOutcome TGFlattenNetworkTestSettingsObjectFallsBackForNonDictionaryInput(void);
TGTestOutcome TGFlattenNetworkTestSettingsRoundTripsThroughBothDirections(void);

#endif
