#ifndef TG_HOST_TESTS_FLATTEN_MESSAGE_CONTENT_TESTS_H
#define TG_HOST_TESTS_FLATTEN_MESSAGE_CONTENT_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGFlattenMessageContentTestMediaInfoForPhoto(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForVideo(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForAnimation(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForDocument(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForAudio(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForVoiceNote(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForVideoNote(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForSticker(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoForAnimatedEmoji(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoReturnsNilForUnsupportedKind(void);
TGTestOutcome TGFlattenMessageContentTestMediaInfoReturnsNilForEmptyContent(void);
TGTestOutcome TGFlattenMessageContentTestFlattenEntitiesMapsVariousKindsAndSkipsMalformed(void);
TGTestOutcome TGFlattenMessageContentTestEntityKindStripsPrefixAndPassesThroughOthers(void);
TGTestOutcome TGFlattenMessageContentTestEntityKindFallsBackForNil(void);
TGTestOutcome TGFlattenMessageContentTestSelfDestructImmediateSentinel(void);
TGTestOutcome TGFlattenMessageContentTestSelfDestructZeroAndNegativeReturnNil(void);
TGTestOutcome TGFlattenMessageContentTestSelfDestructPositiveSecondsReturnsTimer(void);
TGTestOutcome TGFlattenMessageContentTestBase64DecodesValidInput(void);
TGTestOutcome TGFlattenMessageContentTestBase64DecodesEmptyInput(void);
TGTestOutcome TGFlattenMessageContentTestBase64DecodesInputNeedingPadding(void);
TGTestOutcome TGFlattenMessageContentTestBase64SkipsInvalidCharacters(void);

#endif
