#ifndef TG_HOST_TESTS_WALLPAPER_REVERT_ELIGIBILITY_TESTS_H
#define TG_HOST_TESTS_WALLPAPER_REVERT_ELIGIBILITY_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGWallpaperRevertEligibilityTestNonBackgroundMessageIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestOutgoingMessageIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestOnlyForSelfMessageIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestZeroOldBackgroundMessageIdIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestStaleBackgroundIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestMissingCurrentBackgroundIsNotEligible(void);
TGTestOutcome TGWallpaperRevertEligibilityTestCurrentIncomingNotOnlyForSelfBackgroundIsEligible(void);

#endif
