#ifndef TG_HOST_TESTS_CHAT_ACTION_PHRASE_TESTS_H
#define TG_HOST_TESTS_CHAT_ACTION_PHRASE_TESTS_H

#import "../support/tg_test.h"

TGTestOutcome TGChatActionPhraseTestEmptyPhrasesReturnsEmptyString(void);
TGTestOutcome TGChatActionPhraseTestSingleSenderNamesTheVerb(void);
TGTestOutcome TGChatActionPhraseTestTwoSendersSameKindNamesBoth(void);
TGTestOutcome TGChatActionPhraseTestTwoSendersMixedKindFallsBackToGenericVerb(void);
TGTestOutcome TGChatActionPhraseTestThreeOrMoreSendersSameKindNamesFirstAndCountsOthers(void);
TGTestOutcome TGChatActionPhraseTestThreeOrMoreSendersMixedKindFallsBackToGenericVerb(void);
TGTestOutcome TGChatActionPhraseTestMissingSecondDisplayNameDoesNotCrash(void);

#endif
